import { createFormSchema } from "@/shared/form-schema";

export default createFormSchema({
  formMeta: {
    formUuid: "",
    appType: process.env.OPENXIANGDA_APP_TYPE || "APP_XXXX",
    title: "应用角色维护",
  },
  fields: [
    {
      fieldId: "roleCode",
      componentName: "TextField",
      label: "角色编码",
      required: true,
      placeholder: "如 college_admin",
    },
    {
      fieldId: "roleName",
      componentName: "TextField",
      label: "角色名称",
      required: true,
      placeholder: "请输入角色名称",
    },
    {
      fieldId: "members",
      componentName: "UserSelectField",
      label: "成员",
      multiple: true,
      placeholder: "请选择角色成员",
    },
    {
      fieldId: "collegeScope",
      componentName: "SelectField",
      label: "适用学院",
      placeholder: "请选择适用学院",
      showSearch: true,
      allowClear: true,
      options: [],
      valueSync: [{ targetFieldId: "collegeScopeKey", valuePath: "value" }],
      optionSource: {
        type: "linkedForm",
        linkedForm: {
          formUuid: "FORM_COLLEGE_PROFILE",
          fieldId: "collegeName",
          labelFieldId: "collegeName",
          valueFieldId: "collegeCode",
          searchFieldId: "collegeName",
          sortField: "collegeName",
          pageSize: 20,
          remoteSearch: true,
          deduplicate: true,
        },
      },
    },
    {
      fieldId: "classScope",
      componentName: "SelectField",
      label: "适用班级",
      placeholder: "请选择适用班级",
      showSearch: true,
      allowClear: true,
      options: [],
      valueSync: [{ targetFieldId: "classScopeKey", valuePath: "value" }],
      optionSource: {
        type: "linkedForm",
        linkedForm: {
          formUuid: "FORM_CLASS_PROFILE",
          fieldId: "className",
          labelFieldId: "className",
          valueFieldId: "classCode",
          searchFieldId: "className",
          sortField: "className",
          pageSize: 20,
          remoteSearch: true,
          deduplicate: true,
        },
      },
    },
    {
      fieldId: "collegeScopeKey",
      componentName: "TextField",
      label: "学院权限键",
      behavior: "HIDDEN",
    },
    {
      fieldId: "classScopeKey",
      componentName: "TextField",
      label: "班级权限键",
      behavior: "HIDDEN",
    },
    {
      fieldId: "enabled",
      componentName: "RadioField",
      label: "启用状态",
      placeholder: "请选择启用状态",
      defaultValue: { label: "启用", value: "enabled" },
      options: [
        { label: "启用", value: "enabled" },
        { label: "停用", value: "disabled" },
      ],
    },
    {
      fieldId: "lastSyncedAt",
      componentName: "DateField",
      label: "最近同步时间",
      behavior: "HIDDEN",
    },
  ],
});
