// src/tailwind.preset.ts
const syComponentSafelist = [
  'sy-grid',
  'sy-flex',
  'sy-gap-3',
  'sy-gap-4',
  'sy-gap-y-3',
  'sy-gap-y-4',
  'sy-gap-y-5',
  'sy-gap-y-6',
  'sy-gap-y-8',
  'sy-gap-x-4',
  'sy-gap-x-6',
  'sy-gap-x-8',
  'sy-pt-4',
  'sy-mr-2',
  'sy-grid-cols-1',
  'sy-grid-cell',
  'md:sy-grid-cols-2',
  'lg:sy-grid-cols-3',
  'lg:sy-grid-cols-4',
  'sy-form-actions',
  'sy-form-renderer',
  'sy-form-layout',
  'sy-form-section',
  'sy-form-section-plain',
  'sy-form-section-card',
  'sy-form-section-accent-blue',
  'sy-form-section-accent-green',
  'sy-form-section-header',
  'sy-form-section-heading',
  'sy-form-section-marker',
  'sy-form-section-icon',
  'sy-form-section-title-block',
  'sy-form-section-title',
  'sy-form-section-description',
  'sy-form-section-arrow',
  'sy-form-section-content',
  'sy-layout-field',
  'sy-field-wrapper',
  'sy-field-label',
  'sy-field-control',
  'sy-field-readonly-value',
  'sy-field-required',
  'sy-field-tips',
  'sy-field-error',
  'sy-option-color-tag',
  'sy-option-group-colored',
  'sy-option-readonly-list',
  'sy-form-container',
  'sy-form-container-sm',
  'sy-form-container-md',
  'sy-form-container-lg',
  'sy-form-container-xl',
  'sy-form-container-full',
  'sy-form-header',
  'sy-form-title',
  'sy-form-description',
  'sy-form-body',
  'sy-submit-runtime-page',
  'sy-submit-page',
  'sy-submit-card',
  'sy-submit-form-shell',
  'sy-lowcode-page',
  'sy-page-section',
  'sy-page-section-header',
  'sy-page-section-title',
  'sy-page-section-description',
  'sy-page-section-body',
  'sy-page-grid',
  'sy-page-heading',
  'sy-page-text',
  'sy-page-unknown-node',
  'sy-select-with-picker',
  'sy-picker-trigger',
  'sy-org-picker',
  'sy-user-picker',
  'sy-file-list',
  'sy-image-grid',
  'sy-attachment-upload-inline',
  'sy-image-upload-inline',
  'sy-upload-paste-zone',
  'sy-mobile-field-trigger',
  'sy-mobile-line-input',
  'sy-mobile-text-input',
  'sy-mobile-textarea-input',
  'sy-mobile-number-input',
  'sy-mobile-bottom-sheet',
  'sy-mobile-bottom-sheet-content',
  'sy-mobile-option-sheet',
  'sy-mobile-choice-group',
  'sy-mobile-image-grid',
  'sy-mobile-date-sheet',
  'sy-mobile-date-time-picker',
  'sy-mobile-date-range-value',
  'sy-editor',
  'sy-editor-file-input',
  'sy-detail-page',
  'sy-detail-header',
  'sy-detail-header-inner',
  'sy-detail-main',
  'sy-detail-card',
  'sy-detail-summary-panel',
  'sy-summary-panel-content',
  'sy-summary-status-row',
  'sy-summary-title',
  'sy-summary-mobile-identity',
  'sy-summary-mobile-person',
  'sy-summary-mobile-avatar',
  'sy-summary-mobile-person-name',
  'sy-summary-mobile-time',
  'sy-summary-meta-list',
  'sy-summary-meta-item',
  'sy-summary-meta-icon',
  'sy-summary-meta-body',
  'sy-summary-meta-label',
  'sy-summary-meta-value',
  'sy-process-summary',
  'sy-process-summary-with-stamp',
  'sy-process-status-stamp',
  'sy-process-status-stamp-ring',
  'sy-process-status-stamp-text',
  'sy-process-status-stamp-star',
  'sy-process-status-stamp-running',
  'sy-process-status-stamp-approved',
  'sy-process-status-stamp-rejected',
  'sy-process-status-stamp-danger',
  'sy-process-status-stamp-neutral',
  'sy-readonly-files',
  'sy-readonly-images',
  'sy-readonly-attachments',
  'sy-readonly-file-header',
  'sy-readonly-bundle-download',
  'sy-readonly-file-list',
  'sy-readonly-file-item',
  'sy-readonly-image-grid',
  'sy-readonly-image-card',
  'sy-readonly-image-thumb',
  'sy-readonly-image-name',
  'sy-image-preview-overlay',
  'sy-image-preview-mask',
  'sy-image-preview-dialog',
  'sy-image-preview-close',
  'sy-file-size-inline',
  'sy-association-selector',
  'sy-address-mobile',
  'sy-location-field',
  'sy-signature-field',
  'sy-subform',
];

// Components such as DataManagementList, SummaryPanel and workflow/detail templates
// use Tailwind utility classes internally. Keep those classes in the preset so
// consuming workspaces do not depend on scanning this package's private source.
const internalUtilitySafelist = [
  'absolute',
  'after:absolute',
  'after:bg-transparent',
  'after:h-5',
  'after:rounded',
  'after:right-1',
  'after:top-1/2',
  'after:w-0.5',
  'after:-translate-y-1/2',
  'animate-pulse',
  'backdrop-blur',
  'backdrop-blur-lg',
  'bg-amber-50',
  'bg-ant-bg-container',
  'bg-ant-bg-container/95',
  'bg-ant-bg-elevated',
  'bg-ant-bg-layout',
  'bg-blue-50',
  'bg-blue-50/60',
  'bg-blue-100',
  'bg-blue-500',
  'bg-emerald-50',
  'bg-gray-50/70',
  'bg-gray-100',
  'bg-gray-200',
  'bg-green-100',
  'bg-green-500',
  'bg-red-50',
  'bg-white',
  'bg-white/80',
  'block',
  'border',
  'border-2',
  'border-amber-300',
  'border-ant-border-secondary',
  'border-b',
  'border-blue-200',
  'border-blue-300',
  'border-blue-400',
  'border-dashed',
  'border-gray-100',
  'border-gray-200',
  'border-l',
  'border-l-2',
  'border-red-300',
  'border-t',
  'bottom-0',
  'break-words',
  'cursor-col-resize',
  'cursor-pointer',
  'duration-150',
  'duration-1000',
  'fixed',
  'flex',
  'flex-1',
  'flex-col',
  'flex-shrink-0',
  'flex-wrap',
  'font-medium',
  'font-normal',
  'font-semibold',
  'gap-1',
  'gap-1.5',
  'gap-2',
  'gap-3',
  'gap-4',
  'gap-5',
  'grid',
  'grid-cols-1',
  'grid-cols-2',
  'grid-cols-[1fr_auto_1fr]',
  'grid-cols-[minmax(120px,1fr)_120px_minmax(160px,1fr)_auto]',
  'h-0.5',
  'h-1',
  'h-3',
  'h-6',
  'h-7',
  'h-8',
  'h-10',
  'h-11',
  'h-12',
  'h-16',
  'h-full',
  'hidden',
  'hover:after:bg-ant-color-primary',
  'inline-block',
  'inline-flex',
  'items-center',
  'items-end',
  'items-start',
  'justify-between',
  'justify-center',
  'justify-end',
  'justify-start',
  'leading-5',
  'leading-6',
  'leading-9',
  'left-0',
  'left-[21px]',
  'm-0',
  'max-w-4xl',
  'max-w-[1440px]',
  'max-w-[180px]',
  'mb-1',
  'mb-2',
  'mb-3',
  'mb-4',
  'mb-5',
  'mb-6',
  'md:flex-nowrap',
  'md:flex-row',
  'md:grid-cols-2',
  'md:grid-cols-3',
  'md:grid-cols-4',
  'md:grid-cols-[160px_1fr]',
  'md:items-center',
  'md:justify-between',
  'md:-mb-5',
  'md:-mb-6',
  'md:-mx-5',
  'md:-mx-6',
  'md:p-5',
  'md:p-6',
  'md:pb-8',
  'md:px-4',
  'md:px-5',
  'md:px-6',
  'md:py-4',
  'md:py-6',
  'md:text-[28px]',
  'md:w-auto',
  'min-h-0',
  'min-h-6',
  'min-h-[360px]',
  'min-w-0',
  'min-w-[88px]',
  'ml-1',
  'ml-2',
  'ml-4',
  'mr-2',
  'mt-0.5',
  'mt-1',
  'mt-2',
  'mt-3',
  'mt-4',
  'mt-5',
  'mt-6',
  'mx-4',
  'mx-auto',
  'my-1',
  'object-cover',
  'overflow-hidden',
  'overflow-x-auto',
  'p-0',
  'p-4',
  'p-5',
  'p-6',
  'pb-0',
  'pb-4',
  'pb-5',
  'pb-8',
  'pb-24',
  'pl-3',
  'pl-4',
  'pr-3',
  'pt-4',
  'px-1.5',
  'px-2',
  'px-2.5',
  'px-3',
  'px-4',
  'px-5',
  'px-6',
  'py-0.5',
  'py-1',
  'py-2',
  'py-3',
  'py-4',
  'py-6',
  'py-8',
  'py-16',
  'relative',
  'right-0',
  'rounded',
  'rounded-b-lg',
  'rounded-full',
  'rounded-lg',
  'rounded-md',
  'rounded-xl',
  'shadow-[0_-8px_24px_rgba(15,23,42,0.06)]',
  'shadow-[0_0_0_4px_var(--ant-color-bg-layout,#f5f5f5)]',
  'shadow-sm',
  'shrink-0',
  'sm:block',
  'space-y-2',
  'space-y-3',
  'space-y-4',
  'space-y-5',
  'space-y-6',
  'supports-[padding:max(0px)]:pb-[max(0.75rem,env(safe-area-inset-bottom))]',
  'text-2xl',
  'text-amber-700',
  'text-ant-color-text',
  'text-ant-color-text-quaternary',
  'text-ant-color-text-secondary',
  'text-ant-color-text-tertiary',
  'text-ant-primary',
  'text-ant-text',
  'text-ant-text-secondary',
  'text-ant-text-tertiary',
  'text-base',
  'text-blue-500',
  'text-blue-600',
  'text-blue-700',
  'text-center',
  'text-emerald-700',
  'text-gray-300',
  'text-gray-400',
  'text-gray-500',
  'text-gray-600',
  'text-gray-900',
  'text-green-500',
  'text-red-700',
  'text-left',
  'text-lg',
  'text-sm',
  'text-xl',
  'text-xs',
  'top-0',
  'top-11',
  'transition-all',
  'truncate',
  'w-0.5',
  'w-3',
  'w-4',
  'w-6',
  'w-7',
  'w-8',
  'w-10',
  'w-11',
  'w-12',
  'w-48',
  'w-[260px]',
  'w-full',
  'whitespace-nowrap',
  'z-10',
  'z-20',
  '-mb-4',
  '-mx-4',
  '-right-3',
];

const sySafelist = Array.from(new Set([...syComponentSafelist, ...internalUtilitySafelist]));

export default {
  safelist: sySafelist,
  theme: {
    extend: {
      colors: {
        primary: 'var(--sy-color-primary)',
        success: 'var(--sy-color-success)',
        warning: 'var(--sy-color-warning)',
        error: 'var(--sy-color-error)',
        default: 'var(--sy-color-text)',
        secondary: 'var(--sy-color-text-secondary)',
        tertiary: 'var(--sy-color-text-tertiary)',
        disabled: 'var(--sy-color-text-disabled)',
        container: 'var(--sy-color-bg-container)',
        layout: 'var(--sy-color-bg-layout)',
        elevated: 'var(--sy-color-bg-elevated)',
        border: 'var(--sy-color-border)',
        'ant-primary': 'var(--ant-color-primary, #1677ff)',
        'ant-text': 'var(--ant-color-text, rgba(0,0,0,0.88))',
        'ant-text-secondary': 'var(--ant-color-text-secondary, rgba(0,0,0,0.65))',
        'ant-text-tertiary': 'var(--ant-color-text-tertiary, rgba(0,0,0,0.45))',
        'ant-text-quaternary': 'var(--ant-color-text-quaternary, rgba(0,0,0,0.25))',
        'ant-color-primary': 'var(--ant-color-primary, #1677ff)',
        'ant-color-text': 'var(--ant-color-text, rgba(0,0,0,0.88))',
        'ant-color-text-secondary': 'var(--ant-color-text-secondary, rgba(0,0,0,0.65))',
        'ant-color-text-tertiary': 'var(--ant-color-text-tertiary, rgba(0,0,0,0.45))',
        'ant-color-text-quaternary': 'var(--ant-color-text-quaternary, rgba(0,0,0,0.25))',
        'ant-border': 'var(--ant-color-border, #d9d9d9)',
        'ant-border-secondary': 'var(--ant-color-border-secondary, #f0f0f0)',
        'ant-error': 'var(--ant-color-error, #ff4d4f)',
        'ant-success': 'var(--ant-color-success, #52c41a)',
        'ant-warning': 'var(--ant-color-warning, #faad14)',
        'ant-bg-container': 'var(--ant-color-bg-container, #ffffff)',
        'ant-bg-elevated': 'var(--ant-color-bg-elevated, #ffffff)',
        'ant-bg-layout': 'var(--ant-color-bg-layout, #f5f5f5)',
        'ant-split': 'var(--ant-color-split, rgba(0,0,0,0.06))',
      },
      spacing: {
        xs: 'var(--sy-spacing-xs)',
        sm: 'var(--sy-spacing-sm)',
        md: 'var(--sy-spacing-md)',
        lg: 'var(--sy-spacing-lg)',
        xl: 'var(--sy-spacing-xl)',
        'form-gap': 'var(--sy-form-gap, 16px)',
        'form-padding': 'var(--sy-form-padding, 24px)',
        'form-field-height': 'var(--sy-form-field-height, 32px)',
      },
      borderRadius: {
        sm: 'var(--sy-radius-sm)',
        md: 'var(--sy-radius-md)',
        lg: 'var(--sy-radius-lg)',
        form: 'var(--sy-form-radius, 6px)',
      },
      fontSize: {
        'sm-sy': 'var(--sy-font-size-sm)',
        'base-sy': 'var(--sy-font-size-base)',
        'lg-sy': 'var(--sy-font-size-lg)',
        'xl-sy': 'var(--sy-font-size-xl)',
        '2xl-sy': 'var(--sy-font-size-2xl)',
      },
      boxShadow: {
        subtle: 'var(--sy-shadow-sm)',
        card: 'var(--sy-shadow-md)',
        popover: 'var(--sy-shadow-lg)',
      },
    },
  },
  corePlugins: {
    preflight: false,
  },
  plugins: [
    ({ addUtilities, addComponents }: any) => {
      addUtilities(
        {
          '.sy-grid': { display: 'grid' },
          '.sy-flex': { display: 'flex' },
          '.sy-gap-3': { gap: '0.75rem' },
          '.sy-gap-4': { gap: '1rem' },
          '.sy-gap-y-3': { rowGap: '0.75rem' },
          '.sy-gap-y-4': { rowGap: '1rem' },
          '.sy-gap-y-5': { rowGap: '1.25rem' },
          '.sy-gap-y-6': { rowGap: '1.5rem' },
          '.sy-gap-y-8': { rowGap: '2rem' },
          '.sy-gap-x-4': { columnGap: '1rem' },
          '.sy-gap-x-6': { columnGap: '1.5rem' },
          '.sy-gap-x-8': { columnGap: '2rem' },
          '.sy-pt-4': { paddingTop: '1rem' },
          '.sy-mr-2': { marginRight: '0.5rem' },
          '.sy-grid-cols-1': { gridTemplateColumns: 'repeat(1, minmax(0, 1fr))' },
          '.sy-grid-cols-2': { gridTemplateColumns: 'repeat(2, minmax(0, 1fr))' },
          '.sy-grid-cols-3': { gridTemplateColumns: 'repeat(3, minmax(0, 1fr))' },
          '.sy-grid-cols-4': { gridTemplateColumns: 'repeat(4, minmax(0, 1fr))' },
        },
        ['responsive'],
      );

      addComponents({
        '.sy-grid-cell': {
          minWidth: '0',
        },
        '.sy-grid-cell > * + *': {
          marginTop: 'var(--sy-form-field-row-gap, 24px)',
        },
        '.sy-form-layout': {
          display: 'flex',
          flexDirection: 'column',
          gap: 'var(--sy-form-field-row-gap, 24px)',
        },
        '.sy-form-renderer': {
          minWidth: '0',
        },
        '.sy-runtime-page, .sy-form-container, .sy-form-shell, .sy-form-renderer, .sy-lowcode-page':
          {
            '--ant-form-item-margin-bottom': '12px !important',
          },
        '.sy-runtime-page :where(.ant-form, .ant-form-item), .sy-form-container :where(.ant-form, .ant-form-item), .sy-form-shell :where(.ant-form, .ant-form-item), .sy-form-renderer :where(.ant-form, .ant-form-item), .sy-lowcode-page :where(.ant-form, .ant-form-item)':
          {
            '--ant-form-item-margin-bottom': '12px !important',
          },
        '.sy-form-renderer.sy-grid': {
          rowGap: '0',
        },
        '.sy-form-renderer.sy-form-layout, .sy-form-renderer .sy-form-layout': {
          gap: '0',
        },
        '.sy-form-renderer .sy-grid-cell > * + *': {
          marginTop: '0',
        },
        '.sy-runtime-page__content.sy-detail-page': {
          maxWidth: '100% !important',
          padding: '0 !important',
        },
        '.sy-detail-page': {
          width: '100%',
        },
        '.sy-detail-header': {
          width: '100%',
          background: 'var(--ant-color-bg-container, #ffffff)',
          borderBottom: '0',
        },
        '.sy-detail-header-inner': {
          width: '100%',
          maxWidth: '1120px',
          margin: '0 auto',
          padding: '24px 24px 20px',
        },
        '.sy-detail-main': {
          width: '100%',
          maxWidth: '1180px',
          margin: '0 auto',
          padding: '24px 24px 96px',
          display: 'flex',
          flexDirection: 'column',
          gap: '24px',
        },
        '.sy-detail-card': {
          width: '100%',
          border: '1px solid var(--ant-color-border-secondary, #f0f0f0)',
          borderRadius: '8px',
          background: 'var(--ant-color-bg-container, #ffffff)',
          padding: '24px',
        },
        '.sy-detail-summary-panel': {
          border: '0 !important',
          borderRadius: '0 !important',
          boxShadow: 'none !important',
        },
        '.sy-summary-mobile-identity': {
          display: 'none',
        },
        '.sy-process-summary': {
          position: 'relative',
        },
        '.sy-process-summary-with-stamp .sy-summary-panel-content': {
          paddingRight: '168px',
          minHeight: '128px',
        },
        '.sy-process-status-stamp': {
          position: 'absolute',
          top: '18px',
          right: '24px',
          zIndex: '1',
          width: '116px',
          height: '116px',
          color: 'var(--sy-process-status-stamp-color)',
          pointerEvents: 'none',
          userSelect: 'none',
          opacity: '0.92',
          transform: 'rotate(-10deg)',
        },
        '.sy-process-status-stamp-running': {
          '--sy-process-status-stamp-color': '#62c8ee',
        },
        '.sy-process-status-stamp-approved': {
          '--sy-process-status-stamp-color': '#5fd08f',
        },
        '.sy-process-status-stamp-rejected': {
          '--sy-process-status-stamp-color': '#ffc15d',
        },
        '.sy-process-status-stamp-danger': {
          '--sy-process-status-stamp-color': '#ff7875',
        },
        '.sy-process-status-stamp-neutral': {
          '--sy-process-status-stamp-color': '#9ca3af',
        },
        '.sy-process-status-stamp-ring': {
          position: 'relative',
          display: 'block',
          width: '100%',
          height: '100%',
          border: '3px solid currentColor',
          borderRadius: '9999px',
        },
        '.sy-process-status-stamp-ring::before': {
          content: '""',
          position: 'absolute',
          inset: '7px',
          border: '2px solid currentColor',
          borderRadius: '9999px',
        },
        '.sy-process-status-stamp-text': {
          position: 'absolute',
          left: '50%',
          top: '50%',
          transform: 'translate(-50%, -50%) rotate(-22deg)',
          zIndex: '2',
          whiteSpace: 'nowrap',
          fontSize: '24px',
          lineHeight: '1',
          fontWeight: '700',
          letterSpacing: '0',
          textShadow: '0 0 3px #fff, 0 0 5px #fff',
        },
        '.sy-process-status-stamp-star': {
          position: 'absolute',
          transform: 'translate(-50%, -50%)',
          zIndex: '1',
          fontSize: '9px',
          lineHeight: '1',
        },
        '.sy-submit-page': {
          minHeight: '100%',
        },
        '.sy-runtime-page.sy-submit-runtime-page': {
          minHeight: '0',
        },
        '.sy-submit-card': {
          minHeight:
            'var(--sy-submit-card-min-height, max(0px, min(640px, calc(100vh - var(--sy-submit-card-viewport-offset, 220px)))))',
        },
        '.sy-submit-form-shell': {
          display: 'flex !important',
          minHeight: '100%',
          flex: '1 1 auto',
          flexDirection: 'column',
        },
        '.sy-form-section': {
          width: '100%',
          minWidth: '0',
          marginBottom: '16px',
          '--sy-form-section-accent-color': 'var(--ant-color-primary, #1677ff)',
          '--sy-form-section-accent-bg': 'var(--ant-color-primary-bg, #e6f4ff)',
        },
        '.sy-form-section-accent-blue': {
          '--sy-form-section-accent-color': 'var(--ant-color-primary, #1677ff)',
          '--sy-form-section-accent-bg': 'var(--ant-color-primary-bg, #e6f4ff)',
        },
        '.sy-form-section-accent-green': {
          '--sy-form-section-accent-color': 'var(--ant-color-success, #52c41a)',
          '--sy-form-section-accent-bg': 'var(--ant-color-success-bg, #f6ffed)',
        },
        '.sy-form-section-header': {
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'space-between',
          gap: '12px',
          minWidth: '0',
          outline: 'none',
        },
        '.sy-form-section-header[role="button"]': {
          cursor: 'pointer',
        },
        '.sy-form-section-header[role="button"]:focus-visible': {
          borderRadius: '6px',
          boxShadow: '0 0 0 3px var(--ant-control-outline, rgba(22,119,255,0.16))',
        },
        '.sy-form-section-heading': {
          display: 'flex',
          alignItems: 'center',
          minWidth: '0',
        },
        '.sy-form-section-marker': {
          flex: '0 0 auto',
          width: '4px',
          height: '24px',
          marginRight: '12px',
          borderRadius: '999px',
          backgroundColor: 'var(--sy-form-section-accent-color)',
        },
        '.sy-form-section-icon': {
          display: 'inline-flex',
          alignItems: 'center',
          justifyContent: 'center',
          flex: '0 0 auto',
          width: '22px',
          height: '22px',
          marginRight: '12px',
          color: 'var(--sy-form-section-accent-color)',
          fontSize: '20px',
          lineHeight: '1',
        },
        '.sy-form-section-title-block': {
          minWidth: '0',
        },
        '.sy-form-section-title': {
          margin: '0',
          fontSize: '16px',
          lineHeight: '24px',
          fontWeight: '600',
          color: 'var(--ant-color-text, rgba(0,0,0,0.88))',
        },
        '.sy-form-section-description': {
          margin: '4px 0 0',
          fontSize: '13px',
          lineHeight: '20px',
          color: 'var(--ant-color-text-tertiary, rgba(0,0,0,0.45))',
        },
        '.sy-form-section-arrow': {
          flex: '0 0 auto',
          color: 'var(--ant-color-text-tertiary, rgba(0,0,0,0.45))',
          fontSize: '12px',
          lineHeight: '1',
          transition: 'transform 0.2s ease',
        },
        '.sy-form-section-content': {
          minWidth: '0',
          padding: '28px 32px',
          border: '1px solid var(--ant-color-border-secondary, #f0f0f0)',
          borderRadius: '8px',
          background: 'var(--ant-color-bg-container, #ffffff)',
          boxShadow: '0 1px 2px rgba(15, 23, 42, 0.03)',
        },
        '.sy-form-section-plain': {
          background: 'transparent',
          border: '0',
          boxShadow: 'none',
        },
        '.sy-form-section-plain > .sy-form-section-header': {
          marginBottom: '20px',
        },
        '.sy-form-section[data-collapsed="true"] > .sy-form-section-header': {
          marginBottom: '0',
        },
        '.sy-form-section-card': {
          overflow: 'hidden',
          border: '1px solid var(--ant-color-border-secondary, #f0f0f0)',
          borderRadius: '8px',
          background: 'var(--ant-color-bg-container, #ffffff)',
          boxShadow: '0 4px 16px rgba(15, 23, 42, 0.04)',
        },
        '.sy-form-section-card > .sy-form-section-header': {
          marginBottom: '0',
          padding: '18px 24px',
          borderBottom: '1px solid var(--ant-color-split, rgba(0,0,0,0.06))',
          background: 'var(--sy-form-section-accent-bg)',
        },
        '.sy-form-section-card > .sy-form-section-content': {
          padding: '28px 24px 32px',
          border: '0',
          borderRadius: '0',
          boxShadow: 'none',
        },
        '.sy-form-section-card[data-collapsed="true"] > .sy-form-section-header': {
          borderBottom: '0',
        },
        '@media (max-width: 640px)': {
          '.sy-detail-header': {
            background:
              'linear-gradient(180deg, var(--ant-color-primary, #3b82f6) 0 118px, var(--ant-color-bg-layout, #f5f5f5) 118px 100%)',
            padding: '18px 20px 20px',
          },
          '.sy-detail-header-inner': {
            maxWidth: '100%',
            padding: '0',
          },
          '.sy-detail-summary-panel': {
            overflow: 'hidden',
            borderRadius: '12px !important',
            background: 'var(--ant-color-bg-container, #ffffff)',
          },
          '.sy-detail-summary-panel .sy-summary-panel-content': {
            padding: '26px 28px',
          },
          '.sy-detail-summary-panel .sy-summary-status-row': {
            display: 'none',
          },
          '.sy-detail-summary-panel .sy-summary-title': {
            fontSize: '20px',
            lineHeight: '30px',
            fontWeight: '700',
          },
          '.sy-detail-summary-panel .sy-summary-mobile-identity': {
            display: 'flex',
            flexDirection: 'column',
            gap: '8px',
            marginTop: '18px',
            color: 'var(--ant-color-text-secondary, rgba(0,0,0,0.65))',
            fontSize: '15px',
            lineHeight: '23px',
          },
          '.sy-detail-summary-panel .sy-summary-mobile-person': {
            display: 'inline-flex',
            alignItems: 'center',
            minWidth: '0',
            gap: '8px',
          },
          '.sy-detail-summary-panel .sy-summary-mobile-avatar': {
            display: 'inline-flex',
            alignItems: 'center',
            justifyContent: 'center',
            flex: '0 0 auto',
          },
          '.sy-detail-summary-panel .sy-summary-mobile-avatar .ant-avatar': {
            background: 'var(--ant-color-fill-secondary, rgba(0,0,0,0.06))',
            color: 'var(--ant-color-text-tertiary, rgba(0,0,0,0.45))',
          },
          '.sy-detail-summary-panel .sy-summary-mobile-person-name': {
            minWidth: '0',
            overflow: 'hidden',
            textOverflow: 'ellipsis',
            whiteSpace: 'nowrap',
          },
          '.sy-detail-summary-panel .sy-summary-mobile-time': {
            color: 'var(--ant-color-text-tertiary, rgba(0,0,0,0.45))',
            fontSize: '13px',
            lineHeight: '20px',
          },
          '.sy-detail-summary-panel .sy-summary-meta-list': {
            display: 'none',
          },
          '.sy-detail-main': {
            maxWidth: '100%',
            padding: '0 0 96px',
          },
          '.sy-process-summary-with-stamp .sy-summary-panel-content': {
            paddingRight: '112px',
            minHeight: '124px',
          },
          '.sy-process-summary-with-stamp .sy-summary-title': {
            maxWidth: '100%',
          },
          '.sy-process-status-stamp': {
            top: '16px',
            right: '16px',
            width: '82px',
            height: '82px',
          },
          '.sy-process-status-stamp-ring': {
            borderWidth: '2px',
          },
          '.sy-process-status-stamp-ring::before': {
            inset: '5px',
            borderWidth: '1.5px',
          },
          '.sy-process-status-stamp-text': {
            fontSize: '17px',
          },
          '.sy-process-status-stamp-star': {
            fontSize: '6px',
          },
          '.sy-form-section-content': {
            padding: '20px 16px',
          },
          '.sy-form-section-card > .sy-form-section-header': {
            padding: '16px',
          },
          '.sy-form-section-card > .sy-form-section-content': {
            padding: '20px 16px 24px',
          },
        },
        '.sy-layout-field, .sy-layout-field-full': {
          width: '100%',
          minWidth: '0',
        },
        '@media (min-width: 768px)': {
          '.sy-layout-field': {
            maxWidth: '50%',
          },
        },
        // FieldWrapper
        '.sy-field-wrapper': {
          display: 'flex',
          flexDirection: 'column',
          gap: '8px',
          minWidth: '0',
        },
        '.sy-field-label': {
          display: 'inline-flex',
          alignItems: 'center',
          fontSize: '14px',
          lineHeight: '22px',
          color: 'var(--ant-color-text, rgba(0,0,0,0.88))',
          fontWeight: '400',
        },
        '.sy-field-control': {
          '& .ant-input': { width: '100%' },
          '& .ant-select': { width: '100%' },
          '& .ant-picker': { width: '100%' },
          '& .ant-input-number': { width: '100%' },
        },
        '.sy-field-readonly-value': {
          fontSize: '14px',
          lineHeight: '32px',
          color: 'var(--ant-color-text, rgba(0,0,0,0.88))',
          minHeight: '32px',
          padding: '0',
        },
        '.sy-field-required': {
          color: 'var(--ant-color-error, #ff4d4f)',
          marginRight: '4px',
        },
        '.sy-field-tips': {
          color: 'var(--ant-color-text-tertiary, rgba(0,0,0,0.45))',
          fontSize: '12px',
          lineHeight: '18px',
          marginTop: '4px',
        },
        '.sy-field-tips :where(p, ul, ol, blockquote, pre)': {
          marginTop: '0',
          marginBottom: '4px',
        },
        '.sy-field-tips :where(p, ul, ol, blockquote, pre):last-child': {
          marginBottom: '0',
        },
        '.sy-field-error': {
          color: 'var(--ant-color-error, #ff4d4f)',
          fontSize: '12px',
          marginTop: '4px',
        },
        '.sy-option-color-tag': {
          display: 'inline-flex',
          alignItems: 'center',
          justifyContent: 'center',
          minHeight: '22px',
          padding: '1px 8px',
          borderRadius: '4px',
          lineHeight: '20px',
          fontSize: '13px',
          fontWeight: '400',
          whiteSpace: 'nowrap',
          verticalAlign: 'middle',
          marginInlineEnd: '0',
        },
        '.sy-option-group-colored .ant-radio-wrapper, .sy-option-group-colored .ant-checkbox-wrapper':
          {
            alignItems: 'center',
          },
        '.sy-option-group-colored .ant-radio, .sy-option-group-colored .ant-checkbox': {
          alignSelf: 'center',
        },
        '.sy-option-readonly-list': {
          display: 'inline-flex',
          alignItems: 'center',
          flexWrap: 'wrap',
          gap: '4px',
          minHeight: '32px',
        },
        // FormActions
        '.sy-form-actions': {
          display: 'flex',
          justifyContent: 'flex-end',
          gap: '12px',
          paddingTop: '24px',
          marginTop: '8px',
          borderTop: '1px solid var(--ant-color-split, rgba(0,0,0,0.06))',
        },
        // FormContainer
        '.sy-form-container': {
          margin: '0 auto',
          padding: '24px',
          backgroundColor: 'var(--ant-color-bg-container, #ffffff)',
        },
        '.sy-form-container-sm': { maxWidth: '480px' },
        '.sy-form-container-md': { maxWidth: '640px' },
        '.sy-form-container-lg': { maxWidth: '800px' },
        '.sy-form-container-xl': { maxWidth: '960px' },
        '.sy-form-container-full': { maxWidth: '100%' },
        '.sy-form-header': { marginBottom: '24px' },
        '.sy-form-title': {
          fontSize: '20px',
          fontWeight: '600',
          lineHeight: '28px',
          color: 'var(--ant-color-text, rgba(0,0,0,0.88))',
          margin: '0',
        },
        '.sy-form-description': {
          fontSize: '14px',
          color: 'var(--ant-color-text-tertiary, rgba(0,0,0,0.45))',
          marginTop: '4px',
          margin: '4px 0 0 0',
        },
        '.sy-form-body': {},
        // Lowcode page runtime
        '.sy-lowcode-page': {
          display: 'flex',
          flexDirection: 'column',
          gap: '16px',
          minHeight: '100%',
          padding: '16px 24px',
          background: 'var(--ant-color-bg-layout, #f5f5f5)',
          color: 'var(--ant-color-text, rgba(0,0,0,0.88))',
        },
        '.sy-page-section': {
          width: '100%',
          minWidth: '0',
        },
        '.sy-page-section-header': {
          marginBottom: '12px',
        },
        '.sy-page-section-title': {
          margin: '0',
          fontSize: '16px',
          lineHeight: '24px',
          fontWeight: '600',
          color: 'var(--ant-color-text, rgba(0,0,0,0.88))',
        },
        '.sy-page-section-description': {
          margin: '4px 0 0',
          fontSize: '13px',
          lineHeight: '20px',
          color: 'var(--ant-color-text-tertiary, rgba(0,0,0,0.45))',
        },
        '.sy-page-section-body': {
          display: 'flex',
          flexDirection: 'column',
          gap: '16px',
          minWidth: '0',
        },
        '.sy-page-grid': {
          minWidth: '0',
        },
        '.sy-page-heading': {
          margin: '0',
          fontWeight: '600',
          color: 'var(--ant-color-text, rgba(0,0,0,0.88))',
          lineHeight: '1.28',
        },
        'h1.sy-page-heading': { fontSize: '28px' },
        'h2.sy-page-heading': { fontSize: '22px' },
        'h3.sy-page-heading': { fontSize: '18px' },
        'h4.sy-page-heading': { fontSize: '16px' },
        '.sy-page-text': {
          margin: '0',
          fontSize: '14px',
          lineHeight: '22px',
          color: 'var(--ant-color-text-secondary, rgba(0,0,0,0.65))',
        },
        '.sy-page-unknown-node': {
          minWidth: '0',
        },
        // Rich field controls
        '.sy-select-with-picker': {
          display: 'flex',
          gap: '8px',
          alignItems: 'center',
          width: '100%',
          minWidth: '0',
        },
        '.sy-picker-trigger': {
          flex: '0 0 auto',
          height: '32px',
          minWidth: '56px',
          padding: '0 12px',
          border: '1px solid var(--ant-color-border, #d9d9d9)',
          borderRadius: '6px',
          background: 'var(--ant-color-bg-container, #fff)',
          color: 'var(--ant-color-primary, #1677ff)',
          fontSize: '14px',
          lineHeight: '30px',
          cursor: 'pointer',
          transition: 'all 0.2s',
        },
        '.sy-picker-trigger:hover:not(:disabled)': {
          borderColor: 'var(--ant-color-primary-hover, #4096ff)',
          color: 'var(--ant-color-primary-hover, #4096ff)',
          background: 'var(--ant-color-primary-bg, #e6f4ff)',
        },
        '.sy-picker-trigger:disabled': {
          cursor: 'not-allowed',
          color: 'var(--ant-color-text-disabled, rgba(0,0,0,0.25))',
          borderColor: 'var(--ant-color-border, #d9d9d9)',
          background: 'var(--ant-color-fill-quaternary, rgba(0,0,0,0.02))',
        },
        '.sy-empty': {
          color: 'var(--ant-color-text-tertiary, rgba(0,0,0,0.45))',
          padding: '16px',
          textAlign: 'center',
        },
        // Organization picker
        '.sy-org-picker, .sy-user-picker': {
          display: 'flex',
          flexDirection: 'column',
          gap: '12px',
        },
        '.sy-org-picker-main': {
          display: 'grid',
          gridTemplateColumns: 'minmax(320px, 1fr) minmax(150px, 220px)',
          gap: '12px',
          height: 'min(560px, calc(100vh - 240px))',
          minHeight: '420px',
          minWidth: '0',
        },
        '.sy-user-picker-main': {
          display: 'grid',
          gridTemplateColumns: 'minmax(300px, 38%) minmax(260px, 1fr)',
          gridTemplateRows: 'minmax(420px, 1fr) minmax(96px, 150px)',
          gap: '12px',
          height: 'min(620px, calc(100vh - 240px))',
          minHeight: '500px',
          minWidth: '0',
        },
        '.sy-org-picker-tree, .sy-user-picker-depts, .sy-user-picker-members': {
          minWidth: '0',
          border: '1px solid var(--ant-color-border-secondary, #f0f0f0)',
          borderRadius: '6px',
          padding: '8px',
          overflow: 'auto',
        },
        '.sy-user-picker-depts': {
          gridColumn: '1',
          gridRow: '1',
        },
        '.sy-user-picker-members': {
          gridColumn: '2',
          gridRow: '1 / span 2',
          display: 'flex',
          flexDirection: 'column',
          minHeight: '0',
          overflow: 'hidden',
        },
        '.sy-user-picker-member-panel': {
          flex: '1',
          minHeight: '0',
          display: 'flex',
          flexDirection: 'column',
          overflow: 'hidden',
        },
        '.sy-user-picker-member-spin': {
          flex: '1',
          minHeight: '0',
          display: 'flex',
          flexDirection: 'column',
          overflow: 'hidden',
        },
        '.sy-user-picker-member-spin > .ant-spin-container': {
          flex: '1',
          minHeight: '0',
          display: 'flex',
          flexDirection: 'column',
          overflow: 'hidden',
        },
        '.sy-user-picker-members > .ant-spin-nested-loading, .sy-user-picker-members > .ant-spin-nested-loading > .ant-spin-container':
          {
            minHeight: '0',
            flex: '1',
            display: 'flex',
            flexDirection: 'column',
          },
        '.sy-user-picker-list': {
          flex: '1',
          minHeight: '0',
          overflow: 'auto',
        },
        '.sy-user-picker-row': {
          display: 'flex',
          alignItems: 'center',
          gap: '8px',
          width: '100%',
          border: '0',
          background: 'transparent',
          padding: '8px',
          textAlign: 'left',
          cursor: 'pointer',
          borderRadius: '4px',
        },
        '.sy-user-picker-row:hover, .sy-user-picker-row.is-active': {
          background: 'var(--ant-control-item-bg-hover, rgba(0,0,0,0.04))',
        },
        '.sy-user-picker-pagination': {
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'space-between',
          gap: '8px',
          paddingTop: '8px',
          borderTop: '1px solid var(--ant-color-border-secondary, #f0f0f0)',
          color: 'var(--ant-color-text-secondary, rgba(0,0,0,0.65))',
          fontSize: '12px',
        },
        '.sy-org-picker-selected, .sy-user-picker-selected': {
          border: '1px solid var(--ant-color-border-secondary, #f0f0f0)',
          borderRadius: '6px',
          padding: '8px',
          minWidth: '0',
          overflow: 'auto',
        },
        '.sy-user-picker-selected': {
          gridColumn: '1',
          gridRow: '2',
          maxHeight: '150px',
        },
        '.sy-org-picker-selected-head': {
          display: 'flex',
          justifyContent: 'space-between',
          alignItems: 'center',
          marginBottom: '8px',
        },
        '.sy-org-picker-tags': {
          display: 'flex',
          flexWrap: 'wrap',
          gap: '6px',
        },
        '.sy-org-picker-footer': {
          display: 'flex',
          justifyContent: 'flex-end',
          gap: '8px',
        },
        '.sy-org-picker-mobile, .sy-user-picker-mobile, .sy-address-mobile': {
          height: '100%',
          display: 'flex',
          flexDirection: 'column',
          background: 'var(--ant-color-bg-container, #fff)',
          minWidth: '0',
        },
        '.sy-org-picker-mobile .adm-search-bar, .sy-user-picker-mobile .adm-search-bar': {
          flex: '0 0 auto',
          margin: '12px',
        },
        '.sy-org-picker-mobile .adm-list, .sy-user-picker-mobile .adm-list': {
          '--border-top': '0',
          '--border-bottom': '0',
          flex: '0 0 auto',
        },
        '.sy-org-picker-mobile .adm-list-body, .sy-user-picker-mobile .adm-list-body': {
          borderTop: '0',
          borderBottom: '0',
        },
        '.sy-user-picker-mobile .sy-user-picker-member-panel': {
          flex: '1',
          minHeight: '0',
        },
        '.sy-user-picker-mobile .sy-user-picker-list': {
          flex: '1',
          minHeight: '0',
          overflow: 'auto',
        },
        '.sy-user-picker-mobile .sy-user-picker-pagination': {
          display: 'none',
        },
        '.sy-user-picker-mobile .sy-user-picker-selected, .sy-org-picker-mobile .sy-org-picker-selected':
          {
            flex: '0 0 auto',
            maxHeight: '128px',
            border: '0',
            borderTop: '1px solid var(--ant-color-border-secondary, #f0f0f0)',
            borderRadius: '0',
            padding: '10px 12px calc(10px + env(safe-area-inset-bottom))',
          },
        '.sy-org-picker-mobile-head, .sy-address-mobile-head': {
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'space-between',
          padding: '12px',
          borderBottom: '1px solid var(--ant-color-split, rgba(0,0,0,0.06))',
        },
        '.sy-org-picker-mobile-head button, .sy-address-mobile-head button, .sy-address-mobile-path button':
          {
            border: '0',
            background: 'transparent',
            color: 'var(--ant-color-primary, #1677ff)',
            cursor: 'pointer',
          },
        '.sy-org-picker-breadcrumb, .sy-address-mobile-path': {
          display: 'flex',
          gap: '6px',
          flexWrap: 'wrap',
          padding: '8px 12px',
          borderBottom: '1px solid var(--ant-color-split, rgba(0,0,0,0.06))',
          maxWidth: '100%',
          overflowX: 'auto',
        },
        '.sy-address-mobile-path .is-active': {
          fontWeight: '600',
          color: 'var(--ant-color-text, rgba(0,0,0,0.88))',
        },
        '.sy-address-mobile-list': {
          flex: '1',
          overflow: 'auto',
          padding: '8px',
        },
        '.sy-address-mobile-list button': {
          display: 'block',
          width: '100%',
          border: '0',
          background: 'transparent',
          padding: '10px 8px',
          textAlign: 'left',
          borderRadius: '4px',
        },
        '.sy-address-mobile-list button.is-active': {
          background: 'var(--ant-control-item-bg-active, #e6f4ff)',
          color: 'var(--ant-color-primary, #1677ff)',
        },
        '.sy-address-mobile-detail, .sy-address-mobile-footer': {
          padding: '12px',
          borderTop: '1px solid var(--ant-color-split, rgba(0,0,0,0.06))',
        },
        '.sy-address-mobile-trigger': {
          minWidth: '0',
          overflow: 'hidden',
          textOverflow: 'ellipsis',
          whiteSpace: 'nowrap',
        },
        '.sy-address-mobile-trigger > span': {
          display: 'block',
          overflow: 'hidden',
          textOverflow: 'ellipsis',
          whiteSpace: 'nowrap',
        },
        '.sy-address-mobile-footer': {
          display: 'flex',
          justifyContent: 'flex-end',
          gap: '8px',
        },
        // Mobile field primitives
        '.sy-mobile-field-trigger': {
          width: '100%',
          minHeight: '64px',
          display: 'flex',
          alignItems: 'center',
          gap: '10px',
          border: '0',
          borderBottom: '1px solid var(--ant-color-border-secondary, #f0f0f0)',
          background: 'transparent',
          padding: '8px 0 14px',
          color: 'var(--ant-color-text, rgba(0,0,0,0.88))',
          fontSize: '18px',
          lineHeight: '28px',
          textAlign: 'left',
          cursor: 'pointer',
        },
        '.sy-mobile-field-trigger.is-disabled': {
          color: 'var(--ant-color-text-disabled, rgba(0,0,0,0.25))',
          cursor: 'not-allowed',
        },
        '.sy-mobile-field-trigger-text': {
          flex: '1',
          minWidth: '0',
          overflow: 'hidden',
          textOverflow: 'ellipsis',
          whiteSpace: 'nowrap',
        },
        '.sy-mobile-field-trigger-text.is-placeholder': {
          color: 'var(--ant-color-text-tertiary, rgba(0,0,0,0.45))',
        },
        '.sy-mobile-date-range-value': {
          fontSize: '16px',
          lineHeight: '24px',
        },
        '.sy-mobile-field-arrow': {
          flex: '0 0 auto',
          color: 'var(--ant-color-text-quaternary, rgba(0,0,0,0.25))',
          fontSize: '18px',
        },
        '.sy-mobile-field-clear': {
          flex: '0 0 auto',
          display: 'inline-flex',
          alignItems: 'center',
          justifyContent: 'center',
          width: '28px',
          height: '28px',
          color: 'var(--ant-color-text-quaternary, rgba(0,0,0,0.25))',
        },
        '.sy-mobile-line-input': {
          width: '100%',
          minHeight: '56px',
          display: 'flex',
          alignItems: 'center',
          gap: '8px',
          borderBottom: '1px solid var(--ant-color-border-secondary, #f0f0f0)',
          background: 'transparent',
          padding: '6px 0 12px',
          color: 'var(--ant-color-text, rgba(0,0,0,0.88))',
        },
        '.sy-mobile-line-input .adm-input, .sy-mobile-line-input .adm-text-area': {
          flex: '1',
          minWidth: '0',
          '--font-size': '16px',
          '--color': 'var(--ant-color-text, rgba(0,0,0,0.88))',
          '--placeholder-color': 'var(--ant-color-text-tertiary, rgba(0,0,0,0.45))',
        },
        '.sy-mobile-line-input .adm-input-element, .sy-mobile-line-input .adm-text-area-element': {
          lineHeight: '24px',
          border: '0',
          outline: '0',
          boxShadow: 'none',
          appearance: 'none',
          WebkitAppearance: 'none',
          background: 'transparent',
          padding: '0',
          margin: '0',
        },
        '.sy-mobile-line-input .adm-text-area-element': {
          resize: 'none',
        },
        '.sy-mobile-line-input .adm-input-clear': {
          color: 'var(--ant-color-text-quaternary, rgba(0,0,0,0.25))',
        },
        '.sy-mobile-textarea-input': {
          alignItems: 'flex-start',
          minHeight: '92px',
        },
        '.sy-mobile-textarea-input .adm-text-area-count': {
          color: 'var(--ant-color-text-tertiary, rgba(0,0,0,0.45))',
          fontSize: '13px',
          paddingTop: '6px',
        },
        '.sy-mobile-number-input .sy-number-unit-prefix, .sy-mobile-number-input .sy-number-unit-suffix, .sy-mobile-text-input .sy-input-prefix, .sy-mobile-text-input .sy-input-suffix':
          {
            flex: '0 0 auto',
            color: 'var(--ant-color-text-secondary, rgba(0,0,0,0.65))',
            fontSize: '15px',
            lineHeight: '22px',
          },
        '.sy-mobile-text-input .sy-input-count': {
          flex: '0 0 auto',
          color: 'var(--ant-color-text-tertiary, rgba(0,0,0,0.45))',
          fontSize: '13px',
          lineHeight: '20px',
        },
        '.sy-mobile-bottom-sheet': {
          overflow: 'hidden',
          borderRadius: '10px 10px 0 0',
          background: 'var(--ant-color-bg-container, #fff)',
        },
        '.sy-mobile-bottom-sheet-content': {
          height: '100%',
          minHeight: '0',
        },
        '.sy-mobile-sheet-header': {
          display: 'grid',
          gridTemplateColumns: '88px 1fr 88px',
          alignItems: 'center',
          minHeight: '58px',
          padding: '0 12px',
          borderBottom: '1px solid var(--ant-color-border-secondary, #f0f0f0)',
        },
        '.sy-mobile-sheet-title': {
          minWidth: '0',
          overflow: 'hidden',
          textOverflow: 'ellipsis',
          whiteSpace: 'nowrap',
          textAlign: 'center',
          fontSize: '18px',
          lineHeight: '26px',
          fontWeight: '500',
        },
        '.sy-mobile-sheet-action': {
          border: '0',
          background: 'transparent',
          color: 'var(--ant-color-text, rgba(0,0,0,0.88))',
          fontSize: '17px',
          lineHeight: '24px',
          cursor: 'pointer',
          textAlign: 'left',
        },
        '.sy-mobile-sheet-action.is-primary': {
          color: 'var(--ant-color-primary, #1677ff)',
          textAlign: 'right',
        },
        '.sy-mobile-sheet-action:disabled': {
          color: 'var(--ant-color-text-disabled, rgba(0,0,0,0.25))',
          cursor: 'not-allowed',
        },
        '.sy-mobile-search': {
          height: '48px',
          display: 'flex',
          alignItems: 'center',
          gap: '8px',
          padding: '0 14px',
          borderRadius: '6px',
          background: 'var(--ant-color-fill-quaternary, rgba(0,0,0,0.04))',
          color: 'var(--ant-color-text-tertiary, rgba(0,0,0,0.45))',
        },
        '.sy-mobile-search input': {
          flex: '1',
          minWidth: '0',
          border: '0',
          outline: '0',
          background: 'transparent',
          fontSize: '18px',
          color: 'var(--ant-color-text, rgba(0,0,0,0.88))',
        },
        '.sy-mobile-option-sheet': {
          height: '100%',
          display: 'flex',
          flexDirection: 'column',
          minHeight: '0',
        },
        '.sy-mobile-option-search': {
          padding: '14px 14px 16px',
          borderBottom: '1px solid var(--ant-color-border-secondary, #f0f0f0)',
        },
        '.sy-mobile-option-list': {
          flex: '1',
          minHeight: '0',
          overflowY: 'auto',
        },
        '.sy-mobile-option-row': {
          width: '100%',
          minHeight: '64px',
          display: 'flex',
          alignItems: 'center',
          gap: '14px',
          border: '0',
          borderBottom: '1px solid var(--ant-color-border-secondary, #f0f0f0)',
          background: 'transparent',
          padding: '0 16px',
          textAlign: 'left',
          color: 'var(--ant-color-text, rgba(0,0,0,0.88))',
          fontSize: '18px',
          cursor: 'pointer',
        },
        '.sy-mobile-option-row:disabled': {
          color: 'var(--ant-color-text-disabled, rgba(0,0,0,0.25))',
          cursor: 'not-allowed',
        },
        '.sy-mobile-option-check': {
          flex: '0 0 auto',
          width: '22px',
          height: '22px',
          border: '2px solid #c8cdd2',
          background: '#fff',
        },
        '.sy-mobile-option-check.is-radio': {
          borderRadius: '999px',
        },
        '.sy-mobile-option-check.is-checkbox': {
          borderRadius: '5px',
        },
        '.sy-mobile-option-row.is-active .sy-mobile-option-check': {
          borderColor: 'var(--ant-color-primary, #1677ff)',
          background: 'var(--ant-color-primary, #1677ff)',
          boxShadow: 'inset 0 0 0 4px #fff',
        },
        '.sy-mobile-option-label': {
          minWidth: '0',
          overflow: 'hidden',
          textOverflow: 'ellipsis',
          whiteSpace: 'nowrap',
        },
        '.sy-mobile-sheet-footer': {
          flex: '0 0 auto',
          borderTop: '1px solid var(--ant-color-border-secondary, #f0f0f0)',
          padding: '12px 18px calc(12px + env(safe-area-inset-bottom))',
          background: 'var(--ant-color-bg-container, #fff)',
        },
        '.sy-mobile-sheet-count': {
          marginBottom: '12px',
          fontSize: '18px',
          lineHeight: '26px',
          color: 'var(--ant-color-text, rgba(0,0,0,0.88))',
        },
        '.sy-mobile-sheet-count span': {
          color: 'var(--ant-color-primary, #1677ff)',
          margin: '0 4px',
        },
        '.sy-mobile-sheet-footer-actions': {
          display: 'grid',
          gridTemplateColumns: '1fr 1fr',
          gap: '12px',
        },
        '.sy-mobile-sheet-button': {
          height: '52px',
          border: '1px solid var(--ant-color-border, #d9d9d9)',
          borderRadius: '8px',
          background: 'var(--ant-color-bg-container, #fff)',
          color: 'var(--ant-color-text, rgba(0,0,0,0.88))',
          fontSize: '18px',
          cursor: 'pointer',
        },
        '.sy-mobile-sheet-button.is-primary': {
          borderColor: 'var(--ant-color-primary, #1677ff)',
          background: 'var(--ant-color-primary, #1677ff)',
          color: '#fff',
        },
        '.sy-mobile-choice-group': {
          display: 'flex',
          flexWrap: 'wrap',
          gap: '12px 28px',
          padding: '4px 0 12px',
          borderBottom: '1px solid var(--ant-color-border-secondary, #f0f0f0)',
        },
        '.sy-mobile-choice-group.is-vertical': {
          flexDirection: 'column',
          gap: '10px',
        },
        '.sy-mobile-choice-item': {
          display: 'inline-flex',
          alignItems: 'center',
          gap: '8px',
          minHeight: '32px',
          border: '0',
          background: 'transparent',
          padding: '0',
          color: 'var(--ant-color-text, rgba(0,0,0,0.88))',
          fontSize: '16px',
          lineHeight: '24px',
          cursor: 'pointer',
        },
        '.sy-mobile-choice-item:disabled': {
          color: 'var(--ant-color-text-disabled, rgba(0,0,0,0.25))',
          cursor: 'not-allowed',
        },
        '.sy-mobile-choice-control': {
          width: '22px',
          height: '22px',
          border: '2px solid #c8cdd2',
          background: '#fff',
        },
        '.sy-mobile-choice-item.is-radio .sy-mobile-choice-control': {
          borderRadius: '999px',
        },
        '.sy-mobile-choice-item.is-checkbox .sy-mobile-choice-control': {
          borderRadius: '5px',
        },
        '.sy-mobile-choice-item.is-active .sy-mobile-choice-control': {
          borderColor: 'var(--ant-color-primary, #1677ff)',
          background: 'var(--ant-color-primary, #1677ff)',
          boxShadow: 'inset 0 0 0 4px #fff',
        },
        '.sy-mobile-date-sheet .adm-calendar': {
          '--cell-size': '52px',
          paddingBottom: '12px',
        },
        '.sy-mobile-date-sheet .adm-calendar-header': {
          minHeight: '56px',
          borderBottom: '1px solid var(--ant-color-border-secondary, #f0f0f0)',
        },
        '.sy-mobile-date-sheet .adm-calendar-title': {
          fontSize: '20px',
          fontWeight: '600',
        },
        '.sy-mobile-date-time-footer': {
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'space-between',
          gap: '12px',
          padding: '10px 28px 20px',
          fontSize: '18px',
          color: 'var(--ant-color-text, rgba(0,0,0,0.88))',
        },
        '.sy-mobile-date-time-label': {
          border: '0',
          background: 'transparent',
          color: 'var(--ant-color-text, rgba(0,0,0,0.88))',
          fontSize: '18px',
          cursor: 'pointer',
        },
        '.sy-mobile-time-pill': {
          minWidth: '118px',
          minHeight: '44px',
          border: '0',
          borderRadius: '6px',
          background: 'var(--ant-color-fill-secondary, rgba(0,0,0,0.08))',
          color: 'var(--ant-color-text, rgba(0,0,0,0.88))',
          fontSize: '18px',
          cursor: 'pointer',
        },
        '.sy-mobile-time-pill.is-active': {
          background: 'var(--ant-color-primary, #1677ff)',
          color: '#fff',
        },
        '.sy-mobile-time-picker': {
          '--height': '336px',
          '--item-height': '58px',
          '--item-font-size': '22px',
        },
        '.sy-mobile-date-time-picker': {
          '--item-font-size': '20px',
        },
        '.sy-mobile-date-time-picker .adm-picker-view-column:first-child': {
          flex: '1.55',
          minWidth: '126px',
        },
        '.sy-mobile-date-time-picker .adm-picker-view-column:first-child .adm-picker-view-column-item':
          {
            padding: '0 2px',
            fontSize: '17px',
          },
        '.sy-mobile-date-time-picker .adm-picker-view-column:first-child .adm-picker-view-column-item-label':
          {
            overflow: 'visible',
            textOverflow: 'clip',
            whiteSpace: 'nowrap',
          },
        // Files and images
        '.sy-upload-inline': {
          display: 'inline-flex',
          alignItems: 'center',
          gap: '12px',
          minHeight: '40px',
          maxWidth: '100%',
          padding: '4px',
          border: '1px dashed var(--ant-color-border, #d9d9d9)',
          borderRadius: '8px',
          background: 'var(--ant-color-bg-container, #fff)',
          color: 'var(--ant-color-text-tertiary, rgba(0,0,0,0.45))',
        },
        '.sy-upload-inline > .ant-upload': {
          display: 'inline-flex',
          flex: '0 0 auto',
        },
        '.sy-image-upload-inline, .sy-attachment-upload-inline': {
          width: 'min(100%, 408px)',
        },
        '.sy-upload-button': {
          display: 'inline-flex',
          alignItems: 'center',
          justifyContent: 'center',
          gap: '6px',
          minHeight: '34px',
          padding: '4px 14px',
          border: '1px solid var(--ant-color-border, #d9d9d9)',
          borderRadius: '6px',
          background: 'var(--ant-color-bg-container, #fff)',
          color: 'var(--ant-color-text, rgba(0,0,0,0.88))',
          cursor: 'pointer',
          fontSize: '14px',
        },
        '.sy-upload-button:disabled': {
          color: 'var(--ant-color-text-disabled, rgba(0,0,0,0.25))',
          cursor: 'not-allowed',
        },
        '.sy-upload-paste-zone': {
          display: 'inline-flex',
          flex: '1 1 auto',
          alignItems: 'center',
          minWidth: '210px',
          minHeight: '34px',
          padding: '0 10px',
          borderRadius: '6px',
          outline: 'none',
          cursor: 'text',
          userSelect: 'text',
          whiteSpace: 'nowrap',
          color: 'var(--ant-color-text-tertiary, rgba(0,0,0,0.45))',
        },
        '.sy-upload-paste-zone:hover, .sy-upload-paste-zone:focus-visible': {
          background: 'var(--ant-control-item-bg-hover, rgba(0,0,0,0.04))',
        },
        '.sy-upload-paste-zone:focus-visible': {
          boxShadow: '0 0 0 3px var(--ant-control-outline, rgba(22,119,255,0.16))',
        },
        '.sy-upload-paste-zone.is-disabled': {
          cursor: 'not-allowed',
          userSelect: 'none',
          color: 'var(--ant-color-text-disabled, rgba(0,0,0,0.25))',
        },
        '.sy-sr-only': {
          position: 'absolute',
          width: '1px',
          height: '1px',
          padding: '0',
          margin: '-1px',
          overflow: 'hidden',
          clip: 'rect(0, 0, 0, 0)',
          whiteSpace: 'nowrap',
          border: '0',
        },
        '.sy-file-list': {
          display: 'flex',
          flexDirection: 'column',
          gap: '8px',
          marginTop: '8px',
        },
        '.sy-file-item': {
          display: 'flex',
          alignItems: 'center',
          gap: '10px',
          minHeight: '76px',
          padding: '10px 14px',
          border: '0',
          borderRadius: '8px',
          background: 'var(--ant-color-fill-quaternary, #f5f5f5)',
        },
        '.sy-file-icon': {
          width: '46px',
          height: '46px',
          borderRadius: '6px',
          display: 'inline-flex',
          flexDirection: 'column',
          alignItems: 'center',
          justifyContent: 'center',
          gap: '1px',
          background: '#9099a3',
          fontSize: '10px',
          lineHeight: '12px',
          color: '#fff',
          overflow: 'hidden',
        },
        '.sy-file-icon svg': {
          fontSize: '22px',
        },
        '.sy-file-icon-pdf': {
          background: '#e74c3c',
        },
        '.sy-file-icon-excel': {
          background: '#38b77a',
        },
        '.sy-file-icon-word': {
          background: '#4c8df6',
        },
        '.sy-file-icon-ppt': {
          background: '#f08a3e',
        },
        '.sy-file-icon-image': {
          background: '#6aa8ff',
        },
        '.sy-file-meta': {
          flex: '1',
          minWidth: '0',
        },
        '.sy-file-name': {
          display: 'block',
          fontSize: '16px',
          lineHeight: '24px',
          overflow: 'hidden',
          textOverflow: 'ellipsis',
          whiteSpace: 'nowrap',
        },
        '.sy-file-sub': {
          fontSize: '12px',
          color: 'var(--ant-color-text-tertiary, rgba(0,0,0,0.45))',
        },
        '.sy-file-size-inline': {
          marginLeft: '8px',
          color: 'var(--ant-color-text-tertiary, rgba(0,0,0,0.45))',
          fontWeight: '400',
        },
        '.sy-file-actions': {
          display: 'flex',
          alignItems: 'center',
          gap: '12px',
          flex: '0 0 auto',
        },
        '.sy-file-action': {
          border: '0',
          padding: '0',
          background: 'transparent',
          color: 'var(--ant-color-text-quaternary, rgba(0,0,0,0.35))',
          cursor: 'pointer',
          whiteSpace: 'nowrap',
          fontSize: '18px',
        },
        '.sy-file-action:disabled': {
          color: 'var(--ant-color-text-disabled, rgba(0,0,0,0.25))',
          cursor: 'not-allowed',
        },
        '.sy-readonly-files': {
          width: '100%',
          minWidth: '0',
        },
        '.sy-readonly-file-header': {
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'flex-end',
          minHeight: '20px',
          marginBottom: '8px',
        },
        '.sy-readonly-bundle-download': {
          border: '0',
          padding: '0',
          background: 'transparent',
          color: 'var(--ant-color-primary, #1677ff)',
          cursor: 'pointer',
          fontSize: '14px',
          lineHeight: '20px',
        },
        '.sy-readonly-file-list': {
          marginTop: '0',
        },
        '.sy-readonly-file-item': {
          minHeight: '72px',
          borderRadius: '6px',
          background: 'var(--ant-color-fill-quaternary, #f5f5f5)',
        },
        '.sy-readonly-file-item .sy-file-icon': {
          width: '50px',
          height: '50px',
        },
        '.sy-readonly-file-item .sy-file-name': {
          fontSize: '16px',
          lineHeight: '24px',
          color: 'var(--ant-color-text, rgba(0,0,0,0.88))',
          textDecoration: 'none',
        },
        '.sy-readonly-file-item a.sy-file-name:hover': {
          color: 'var(--ant-color-primary, #1677ff)',
          textDecoration: 'underline',
        },
        '.sy-readonly-file-item .sy-file-actions': {
          gap: '16px',
        },
        '.sy-readonly-file-item .sy-file-action': {
          color: 'var(--ant-color-text-quaternary, rgba(0,0,0,0.35))',
        },
        '.sy-readonly-image-grid': {
          display: 'grid',
          gridTemplateColumns: 'repeat(2, minmax(0, 124px))',
          gap: '12px 16px',
        },
        '.sy-readonly-image-card': {
          minWidth: '0',
        },
        '.sy-readonly-image-thumb': {
          width: '100%',
          aspectRatio: '1 / 1',
          border: '1px solid var(--ant-color-border-secondary, #f0f0f0)',
          borderRadius: '8px',
          padding: '0',
          overflow: 'hidden',
          background: 'var(--ant-color-bg-container, #fff)',
          cursor: 'pointer',
        },
        '.sy-readonly-image-thumb img': {
          width: '100%',
          height: '100%',
          objectFit: 'cover',
          display: 'block',
        },
        '.sy-readonly-image-name': {
          marginTop: '6px',
          overflow: 'hidden',
          textOverflow: 'ellipsis',
          whiteSpace: 'nowrap',
          textAlign: 'center',
          color: 'var(--ant-color-text-tertiary, rgba(0,0,0,0.45))',
          fontSize: '14px',
          lineHeight: '20px',
        },
        '.sy-readonly-files.is-mobile .sy-file-list': {
          gap: '6px',
          marginTop: '0',
        },
        '.sy-readonly-files.is-mobile .sy-readonly-file-item': {
          minHeight: '68px',
          padding: '10px 12px',
          gap: '10px',
        },
        '.sy-readonly-files.is-mobile .sy-file-icon': {
          width: '48px',
          height: '48px',
          borderRadius: '4px',
        },
        '.sy-readonly-files.is-mobile .sy-file-name': {
          fontSize: '15px',
          lineHeight: '22px',
        },
        '.sy-readonly-files.is-mobile .sy-file-sub, .sy-readonly-files.is-mobile .sy-file-size-inline':
          {
            fontSize: '14px',
          },
        '.sy-readonly-files.is-mobile .sy-file-actions': {
          gap: '12px',
        },
        '.sy-readonly-files.is-mobile .sy-file-action': {
          fontSize: '16px',
        },
        '.sy-readonly-files.is-mobile .sy-readonly-bundle-download, .sy-readonly-files.is-mobile .sy-readonly-file-header':
          {
            display: 'none',
          },
        '.sy-image-preview-overlay': {
          position: 'fixed',
          inset: '0',
          zIndex: '1000',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          padding: '24px',
        },
        '.sy-image-preview-mask': {
          position: 'absolute',
          inset: '0',
          border: '0',
          padding: '0',
          background: 'rgba(0,0,0,0.72)',
          cursor: 'zoom-out',
        },
        '.sy-image-preview-dialog': {
          position: 'relative',
          zIndex: '1',
          maxWidth: 'min(920px, 92vw)',
          maxHeight: '88vh',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
        },
        '.sy-image-preview-dialog img': {
          display: 'block',
          maxWidth: '100%',
          maxHeight: '88vh',
          objectFit: 'contain',
          borderRadius: '8px',
          background: '#fff',
        },
        '.sy-image-preview-close': {
          position: 'absolute',
          right: '-14px',
          top: '-14px',
          zIndex: '2',
          width: '32px',
          height: '32px',
          border: '0',
          borderRadius: '999px',
          background: 'rgba(0,0,0,0.68)',
          color: '#fff',
          cursor: 'pointer',
          fontSize: '22px',
          lineHeight: '32px',
        },
        '.sy-mobile-upload-button': {
          display: 'inline-flex',
          alignItems: 'center',
          justifyContent: 'center',
          minHeight: '36px',
          gap: '8px',
          padding: '6px 12px',
          border: '1px solid var(--ant-color-border, #d9d9d9)',
          borderRadius: '8px',
          background: 'var(--ant-color-bg-container, #fff)',
          color: 'var(--ant-color-text, rgba(0,0,0,0.88))',
          cursor: 'pointer',
        },
        '.sy-mobile-upload-button.is-disabled': {
          color: 'var(--ant-color-text-disabled, rgba(0,0,0,0.25))',
          cursor: 'not-allowed',
          background: 'var(--ant-color-fill-quaternary, rgba(0,0,0,0.02))',
        },
        '.sy-mobile-hidden-input': {
          display: 'none',
        },
        '.sy-image-grid': {
          display: 'grid',
          gridTemplateColumns: 'repeat(auto-fill, minmax(96px, 1fr))',
          gap: '8px',
          marginTop: '8px',
        },
        '.sy-image-file-list': {
          maxWidth: '516px',
        },
        '.sy-image-file-thumb': {
          width: '58px',
          height: '58px',
          flex: '0 0 auto',
          border: '1px solid var(--ant-color-border-secondary, #f0f0f0)',
          borderRadius: '8px',
          overflow: 'hidden',
          background: '#fff',
          padding: '0',
          cursor: 'pointer',
        },
        '.sy-image-file-thumb img': {
          width: '100%',
          height: '100%',
          objectFit: 'cover',
        },
        '.sy-mobile-image-grid': {
          display: 'grid',
          gridTemplateColumns: 'repeat(3, minmax(0, 1fr))',
          gap: '10px 12px',
        },
        '.sy-mobile-image-card': {
          position: 'relative',
          minWidth: '0',
        },
        '.sy-mobile-image-thumb': {
          position: 'relative',
          aspectRatio: '1 / 1',
          border: '1px solid var(--ant-color-border-secondary, #f0f0f0)',
          borderRadius: '8px',
          overflow: 'visible',
          background: 'var(--ant-color-fill-quaternary, #f5f5f5)',
        },
        '.sy-mobile-image-thumb .sy-image-preview': {
          width: '100%',
          height: '100%',
          border: '0',
          borderRadius: '8px',
          overflow: 'hidden',
          padding: '0',
          background: 'transparent',
        },
        '.sy-mobile-image-thumb img': {
          width: '100%',
          height: '100%',
          objectFit: 'cover',
        },
        '.sy-mobile-image-thumb .sy-file-action-remove': {
          position: 'absolute',
          right: '-9px',
          top: '-9px',
          zIndex: '2',
          width: '22px',
          height: '22px',
          borderRadius: '999px',
          background: 'rgba(0,0,0,0.38)',
          color: '#fff',
          display: 'inline-flex',
          alignItems: 'center',
          justifyContent: 'center',
          fontSize: '12px',
        },
        '.sy-mobile-image-name': {
          marginTop: '6px',
          minWidth: '0',
          overflow: 'hidden',
          textOverflow: 'ellipsis',
          whiteSpace: 'nowrap',
          color: 'var(--ant-color-text-tertiary, rgba(0,0,0,0.45))',
          fontSize: '14px',
          lineHeight: '20px',
        },
        '.sy-mobile-image-upload-tile': {
          aspectRatio: '1 / 1',
          border: '1px dashed var(--ant-color-border, #d9d9d9)',
          borderRadius: '8px',
          background: 'var(--ant-color-bg-container, #fff)',
          display: 'flex',
          flexDirection: 'column',
          alignItems: 'center',
          justifyContent: 'center',
          gap: '8px',
          color: 'var(--ant-color-text-secondary, rgba(0,0,0,0.65))',
          fontSize: '16px',
          cursor: 'pointer',
        },
        '.sy-mobile-image-upload-tile svg': {
          color: 'var(--ant-color-text-quaternary, rgba(0,0,0,0.35))',
          fontSize: '30px',
        },
        '.sy-image-thumb': {
          position: 'relative',
          aspectRatio: '1 / 1',
          borderRadius: '6px',
          overflow: 'hidden',
          border: '1px solid var(--ant-color-border-secondary, #f0f0f0)',
          background: 'var(--ant-color-fill-tertiary, rgba(0,0,0,0.04))',
        },
        '.sy-image-preview': {
          width: '100%',
          height: '100%',
          border: '0',
          padding: '0',
          background: 'transparent',
          cursor: 'pointer',
        },
        '.sy-image-preview:disabled': {
          cursor: 'default',
        },
        '.sy-image-thumb img': {
          width: '100%',
          height: '100%',
          objectFit: 'cover',
        },
        '.sy-image-state': {
          position: 'absolute',
          inset: '0',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          padding: '8px',
          fontSize: '12px',
          color: 'var(--ant-color-text-secondary, rgba(0,0,0,0.65))',
          textAlign: 'center',
          wordBreak: 'break-all',
          background: 'rgba(255,255,255,0.72)',
        },
        '.sy-image-actions': {
          position: 'absolute',
          right: '4px',
          bottom: '4px',
          zIndex: '2',
          display: 'flex',
          gap: '4px',
          padding: '2px 4px',
          borderRadius: '4px',
          background: 'rgba(255,255,255,0.9)',
          boxShadow: '0 1px 4px rgba(0,0,0,0.08)',
        },
        '.sy-image-actions button': {
          border: '0',
          padding: '0',
          background: 'transparent',
          color: 'var(--ant-color-primary, #1677ff)',
          cursor: 'pointer',
          fontSize: '12px',
          lineHeight: '18px',
        },
        '.sy-image-actions button:disabled': {
          color: 'var(--ant-color-text-disabled, rgba(0,0,0,0.25))',
          cursor: 'not-allowed',
        },
        '.sy-image-meta': {
          position: 'absolute',
          left: '4px',
          top: '4px',
          zIndex: '1',
          maxWidth: 'calc(100% - 8px)',
          padding: '1px 4px',
          borderRadius: '4px',
          background: 'rgba(0,0,0,0.48)',
          color: '#fff',
          fontSize: '11px',
          lineHeight: '16px',
          pointerEvents: 'none',
        },
        // Editor
        '.sy-editor': {
          border: '1px solid var(--ant-color-border, #d9d9d9)',
          borderRadius: '6px',
          background: 'var(--ant-color-bg-container, #fff)',
          overflow: 'hidden',
          transition: 'border-color 0.15s ease, box-shadow 0.15s ease',
        },
        '.sy-editor:focus-within': {
          borderColor: 'var(--ant-color-primary, #1677ff)',
          boxShadow: '0 0 0 1px var(--ant-color-primary, #1677ff)',
        },
        '.sy-editor.is-disabled': {
          background: 'var(--ant-color-fill-quaternary, rgba(0,0,0,0.02))',
        },
        '.sy-editor.is-mobile': {
          border: '0',
          borderBottom: '1px solid var(--ant-color-split, rgba(0,0,0,0.06))',
          borderRadius: '0',
          background: 'transparent',
          boxShadow: 'none',
        },
        '.sy-editor.is-mobile:focus-within': {
          borderBottomColor: 'var(--ant-color-primary, #1677ff)',
          boxShadow: 'none',
        },
        '.sy-editor-toolbar': {
          display: 'flex',
          alignItems: 'center',
          flexWrap: 'nowrap',
          gap: '0',
          minHeight: '44px',
          padding: '6px 12px',
          overflowX: 'auto',
          overflowY: 'hidden',
          scrollbarWidth: 'thin',
          borderBottom: '1px solid var(--ant-color-split, rgba(0,0,0,0.06))',
          background: 'var(--ant-color-fill-quaternary, #f7f8fb)',
        },
        '.sy-editor-toolbar-group': {
          display: 'inline-flex',
          alignItems: 'center',
          flexWrap: 'nowrap',
          gap: '2px',
          padding: '0 8px',
          borderRight: '1px solid var(--ant-color-split, rgba(0,0,0,0.06))',
        },
        '.sy-editor-toolbar-group:first-child': {
          paddingLeft: '0',
        },
        '.sy-editor-toolbar-group:last-child': {
          borderRight: '0',
          paddingRight: '0',
        },
        '.sy-editor-toolbar .ant-btn': {
          minWidth: '30px',
          height: '30px',
          paddingInline: '7px',
          borderColor: 'transparent',
          background: 'transparent',
          boxShadow: 'none',
          color: 'var(--ant-color-text, rgba(0,0,0,0.88))',
        },
        '.sy-editor-toolbar .ant-btn:not(:disabled):hover': {
          borderColor: 'transparent',
          background: 'var(--ant-color-fill-secondary, rgba(0,0,0,0.06))',
          color: 'var(--ant-color-text, rgba(0,0,0,0.88))',
        },
        '.sy-editor-toolbar .ant-btn-primary': {
          borderColor: 'transparent',
          background: 'var(--ant-color-primary-bg, #e6f4ff)',
          color: 'var(--ant-color-primary, #1677ff)',
          boxShadow: 'none',
        },
        '.sy-editor-toolbar-select': {
          flex: '0 0 auto',
          minWidth: '72px',
        },
        '.sy-editor-toolbar-select .ant-select-selector': {
          borderColor: 'transparent !important',
          background: 'transparent !important',
          boxShadow: 'none !important',
          paddingInline: '4px !important',
        },
        '.sy-editor-toolbar-select:hover .ant-select-selector': {
          background: 'var(--ant-color-fill-secondary, rgba(0,0,0,0.06)) !important',
        },
        '.sy-editor-color': {
          width: '30px',
          height: '30px',
          border: '1px solid transparent',
          borderRadius: '4px',
          padding: '3px',
          background: 'transparent',
          cursor: 'pointer',
        },
        '.sy-editor-color:hover': {
          background: 'var(--ant-color-fill-secondary, rgba(0,0,0,0.06))',
        },
        '.sy-editor-color-presets': {
          display: 'inline-flex',
          alignItems: 'center',
        },
        '.sy-editor-swatch': {
          width: '20px',
          height: '20px',
          border: '1px solid rgba(0,0,0,0.08)',
          borderRadius: '4px',
          cursor: 'pointer',
          padding: '0',
        },
        '.sy-editor-file-input': {
          display: 'none !important',
          position: 'absolute !important',
          width: '1px !important',
          height: '1px !important',
          opacity: '0 !important',
          pointerEvents: 'none !important',
        },
        '.sy-editor-body': {
          padding: '28px 44px',
          overflow: 'auto',
          cursor: 'text',
        },
        '.sy-editor.is-mobile .sy-editor-body': {
          padding: '6px 0 12px',
          minHeight: '120px',
          overflow: 'visible',
        },
        '.sy-editor-prose': {
          outline: 'none',
          minHeight: 'inherit',
          whiteSpace: 'pre-wrap',
          fontSize: '14px',
          lineHeight: '22px',
          color: 'var(--ant-color-text, rgba(0,0,0,0.88))',
        },
        '.sy-editor.is-mobile .sy-editor-prose': {
          fontSize: '16px',
          lineHeight: '24px',
        },
        '.sy-editor-readonly': {
          whiteSpace: 'pre-wrap',
        },
        '.sy-summary-richtext': {
          display: 'block',
          maxWidth: '100%',
        },
        '.sy-summary-richtext p': {
          margin: '0 0 4px',
        },
        '.sy-summary-json': {
          margin: '0',
          whiteSpace: 'pre-wrap',
          wordBreak: 'break-word',
          fontFamily:
            'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace',
          fontSize: '12px',
          lineHeight: '1.5',
        },
        '.sy-editor-prose p': { margin: '0 0 8px' },
        '.sy-editor-prose blockquote, .sy-editor-readonly blockquote': {
          margin: '8px 0',
          paddingLeft: '12px',
          borderLeft: '3px solid var(--ant-color-border, #d9d9d9)',
          color: 'var(--ant-color-text-secondary, rgba(0,0,0,0.65))',
        },
        '.sy-editor-prose pre, .sy-editor-readonly pre': {
          margin: '8px 0',
          padding: '10px 12px',
          borderRadius: '6px',
          background: 'var(--ant-color-fill-quaternary, rgba(0,0,0,0.02))',
          overflowX: 'auto',
        },
        '.sy-editor-prose ul[data-type="taskList"], .sy-editor-readonly ul[data-type="taskList"]': {
          paddingLeft: '0',
          listStyle: 'none',
        },
        '.sy-editor-prose li[data-type="taskItem"], .sy-editor-readonly li[data-type="taskItem"]': {
          display: 'flex',
          alignItems: 'flex-start',
          gap: '8px',
        },
        '.sy-editor-prose li[data-type="taskItem"] > label, .sy-editor-readonly li[data-type="taskItem"] > label':
          {
            flex: '0 0 auto',
            marginTop: '2px',
          },
        '.sy-editor-prose li[data-type="taskItem"] > div, .sy-editor-readonly li[data-type="taskItem"] > div':
          {
            minWidth: '0',
            flex: '1',
          },
        '.sy-editor-prose table, .sy-editor-readonly table': {
          borderCollapse: 'collapse',
          width: '100%',
          tableLayout: 'fixed',
          margin: '8px 0',
        },
        '.sy-editor-prose td, .sy-editor-prose th, .sy-editor-readonly td, .sy-editor-readonly th':
          {
            border: '1px solid var(--ant-color-border-secondary, #f0f0f0)',
            padding: '6px',
          },
        '.sy-editor-image': {
          maxWidth: '100%',
          borderRadius: '4px',
        },
        '.sy-editor-footer': {
          display: 'flex',
          justifyContent: 'space-between',
          gap: '8px',
          marginTop: '4px',
          fontSize: '12px',
          color: 'var(--ant-color-text-tertiary, rgba(0,0,0,0.45))',
        },
        '.sy-editor-footer-error': {
          color: 'var(--ant-color-error, #ff4d4f)',
        },
        '.sy-editor-modal-form': {
          display: 'flex',
          flexDirection: 'column',
          gap: '12px',
        },
        '.sy-editor-table-size label': {
          display: 'grid',
          gridTemplateColumns: '48px minmax(0, 1fr)',
          alignItems: 'center',
          gap: '12px',
        },
        // Association and location/signature
        '.sy-association-selector': {
          display: 'flex',
          flexDirection: 'column',
          gap: '12px',
        },
        '.sy-association-selected': {
          display: 'flex',
          flexWrap: 'wrap',
          gap: '6px',
          paddingTop: '4px',
        },
        '.sy-location-field': {
          display: 'flex',
          flexDirection: 'column',
          gap: '8px',
        },
        '.sy-location-meta, .sy-signature-hash': {
          fontSize: '12px',
          color: 'var(--ant-color-text-tertiary, rgba(0,0,0,0.45))',
        },
        '.sy-signature-field': {
          display: 'flex',
          flexDirection: 'column',
          alignItems: 'flex-start',
          gap: '8px',
        },
        '.sy-signature-preview': {
          border: '1px solid var(--ant-color-border-secondary, #f0f0f0)',
          background: 'var(--ant-color-bg-container, #fff)',
          padding: '4px',
          borderRadius: '6px',
        },
        '.sy-signature-preview img': {
          display: 'block',
          maxWidth: '240px',
          maxHeight: '120px',
        },
        '.sy-signature-canvas-wrap': {
          display: 'flex',
          flexDirection: 'column',
          gap: '8px',
        },
        // Subform
        '.sy-subform': {
          display: 'flex',
          flexDirection: 'column',
          gap: '12px',
          width: '100%',
        },
        '.sy-subform-toolbar': {
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'flex-end',
          gap: '12px',
          minHeight: '34px',
        },
        '.sy-subform-row-count': {
          color: 'var(--ant-color-text-secondary, rgba(0,0,0,0.65))',
          fontSize: '14px',
          lineHeight: '22px',
        },
        '.sy-subform-table-wrap': {
          overflowX: 'auto',
          border: '1px solid var(--ant-color-border, #d9d9d9)',
          borderRadius: '8px',
          background: 'var(--ant-color-bg-container, #fff)',
          boxShadow: '0 4px 14px rgba(15, 23, 42, 0.06)',
        },
        '.sy-subform-table': {
          width: '100%',
          minWidth: '720px',
          borderCollapse: 'separate',
          borderSpacing: '0',
        },
        '.sy-subform-table th, .sy-subform-table td': {
          borderBottom: '1px solid var(--ant-color-border-secondary, #f0f0f0)',
          borderRight: '1px solid var(--ant-color-border-secondary, #f0f0f0)',
          textAlign: 'left',
          verticalAlign: 'middle',
        },
        '.sy-subform-table th': {
          padding: '12px 14px',
          color: 'var(--ant-color-text, rgba(0,0,0,0.88))',
          background: 'var(--ant-color-fill-quaternary, #fafafa)',
          fontSize: '14px',
          fontWeight: '600',
          lineHeight: '22px',
          whiteSpace: 'nowrap',
        },
        '.sy-subform-table td': {
          padding: '14px 10px',
          background: 'var(--ant-color-bg-container, #fff)',
        },
        '.sy-subform-table th:last-child, .sy-subform-table td:last-child': {
          borderRight: '0',
          textAlign: 'right',
          width: '88px',
        },
        '.sy-subform-table tbody tr:last-child td': {
          borderBottom: '0',
        },
        '.sy-subform-table tbody tr:hover td': {
          background: 'var(--ant-control-item-bg-hover, #f5f5f5)',
        },
        '.sy-subform-table .sy-field-wrapper': {
          margin: '0',
        },
        '.sy-subform-table .sy-field-label, .sy-subform-table .sy-field-tips': {
          display: 'none',
        },
        '.sy-subform-table .sy-field-control > *': {
          width: '100%',
        },
        '.sy-subform-card': {
          overflow: 'hidden',
          border: '1px solid var(--ant-color-border-secondary, #f0f0f0)',
          borderRadius: '8px',
          background: 'var(--ant-color-bg-container, #fff)',
          boxShadow: '0 2px 10px rgba(15, 23, 42, 0.04)',
        },
        '.sy-subform-card-head': {
          display: 'flex',
          justifyContent: 'space-between',
          alignItems: 'center',
          gap: '10px',
          padding: '10px 12px',
          borderBottom: '1px solid var(--ant-color-border-secondary, #f0f0f0)',
          background: 'var(--ant-color-fill-quaternary, #fafafa)',
        },
        '.sy-subform-card-head strong': {
          display: 'inline-flex',
          alignItems: 'center',
          borderRadius: '6px',
          padding: '2px 8px',
          color: 'var(--ant-color-primary, #1677ff)',
          background: 'var(--ant-color-primary-bg, #e6f4ff)',
          fontSize: '13px',
          lineHeight: '20px',
        },
        '.sy-subform-mobile-cell': {
          display: 'grid',
          gridTemplateColumns: '96px minmax(0, 1fr)',
          gap: '10px',
          alignItems: 'start',
          padding: '10px 12px',
          borderBottom: '1px solid var(--ant-color-border-secondary, #f0f0f0)',
        },
        '.sy-subform-mobile-cell:last-child': {
          borderBottom: '0',
        },
        '.sy-subform-mobile-cell label': {
          paddingTop: '5px',
          color: 'var(--ant-color-text, rgba(0,0,0,0.88))',
          fontSize: '14px',
          lineHeight: '22px',
        },
        '.sy-subform-link-button': {
          border: '0',
          background: 'transparent',
          color: 'var(--ant-color-primary, #1677ff)',
          cursor: 'pointer',
          padding: '0 2px',
          fontSize: '14px',
          lineHeight: '22px',
        },
        '.sy-subform-danger-button': {
          color: 'var(--ant-color-error, #ff4d4f)',
        },
        '.sy-subform-link-button:disabled': {
          color: 'var(--ant-color-text-quaternary, rgba(0,0,0,0.25))',
          cursor: 'not-allowed',
        },
        '.sy-subform-add-button': {
          border: '1px solid var(--ant-color-primary, #1677ff)',
          borderRadius: '6px',
          background: 'var(--ant-color-primary-bg, #e6f4ff)',
          color: 'var(--ant-color-primary, #1677ff)',
          cursor: 'pointer',
          padding: '5px 12px',
          fontSize: '14px',
          lineHeight: '22px',
        },
        '.sy-subform-add-button:disabled': {
          borderColor: 'var(--ant-color-border, #d9d9d9)',
          background: 'var(--ant-color-fill-quaternary, #fafafa)',
          color: 'var(--ant-color-text-quaternary, rgba(0,0,0,0.25))',
          cursor: 'not-allowed',
        },
        '.sy-subform-empty': {
          color: 'var(--ant-color-text-tertiary, rgba(0,0,0,0.45))',
          padding: '10px 12px',
          border: '1px dashed var(--ant-color-border, #d9d9d9)',
          borderRadius: '8px',
          background: 'var(--ant-color-fill-quaternary, #fafafa)',
          textAlign: 'center',
        },
        // Spinner (kept for backward compat)
        '.sy-spinner': {
          width: '14px',
          height: '14px',
          border: '2px solid currentColor',
          borderTopColor: 'transparent',
          borderRadius: '9999px',
          animation: 'sy-spin 0.8s linear infinite',
        },
        '@keyframes sy-spin': {
          to: {
            transform: 'rotate(360deg)',
          },
        },
      });
    },
  ],
};
