import type {
  ActivityItem,
  AdminTemplateMeta,
  MetricItem,
  NavItem,
  NoticeItem,
  QuickAction,
  RankingItem,
  TaskProgressItem,
  TodoItem,
  WorkOrderRecord,
} from "./types";

export const adminTemplateMetas: AdminTemplateMeta[] = [
  {
    key: "glass-home-dashboard",
    uiTemplate: "glass-home-dashboard",
    name: "浅蓝玻璃经营首页",
    recommendedFor: ["经营首页", "管理驾驶舱", "轻量门户首页"],
    description:
      "浅蓝玻璃拟态、欢迎横幅、快捷入口和经营指标，适合默认后台首页。",
  },
  {
    key: "mint-analytics-dashboard",
    uiTemplate: "mint-analytics-dashboard",
    name: "薄荷数据分析首页",
    recommendedFor: ["数据分析", "BI 概览", "经营日报"],
    description:
      "浅绿低饱和数据看板，信息密度更高，适合分析型后台首页。",
  },
  {
    key: "ops-monitor-dashboard",
    uiTemplate: "ops-monitor-dashboard",
    name: "蓝紫运营监控中心",
    recommendedFor: ["运营监控", "任务中心", "系统健康度"],
    description:
      "蓝紫科技感和轻量动态效果，适合实时监控、告警、系统状态页面。",
  },
  {
    key: "work-order-list-drawer",
    uiTemplate: "work-order-list-drawer",
    name: "工单列表抽屉模板",
    recommendedFor: ["CRUD 列表", "工单管理", "审批处理", "数据管理页"],
    description:
      "克制型后台列表页，右侧详情和表单抽屉覆盖展示，不挤占主表格。",
  },
];

export const standardNavItems: NavItem[] = [
  { key: "home", label: "首页总览", icon: "home" },
  { key: "analytics", label: "数据分析", icon: "analytics" },
  { key: "business", label: "业务运营", icon: "business" },
  { key: "customer", label: "客户管理", icon: "customer" },
  { key: "order", label: "订单管理", icon: "order" },
  { key: "product", label: "产品管理", icon: "product" },
  { key: "finance", label: "财务中心", icon: "finance" },
  { key: "system", label: "系统管理", icon: "system" },
  { key: "app", label: "应用中心", icon: "app" },
];

export const monitorNavItems: NavItem[] = [
  { key: "home", label: "首页", icon: "home" },
  { key: "overview", label: "数据总览", icon: "analytics" },
  { key: "monitor", label: "监控中心", icon: "monitor" },
  { key: "operation", label: "运营管理", icon: "business" },
  { key: "task", label: "任务管理", icon: "task" },
  { key: "alert", label: "告警中心", icon: "alert" },
  { key: "device", label: "设备管理", icon: "device" },
  { key: "user", label: "用户管理", icon: "user" },
  { key: "report", label: "报表中心", icon: "report" },
  { key: "system", label: "系统管理", icon: "system" },
];

export const workOrderNavItems: NavItem[] = [
  { key: "workbench", label: "运营工作台", icon: "dashboard" },
  {
    key: "ticket",
    label: "工单管理",
    icon: "ticket",
    children: [
      { key: "ticket-list", label: "工单列表", icon: "ticket" },
      { key: "created-by-me", label: "我创建的", icon: "user" },
      { key: "assigned-to-me", label: "我处理的", icon: "task" },
      { key: "copied-to-me", label: "抄送我的", icon: "business" },
    ],
  },
  { key: "approval", label: "流程审批", icon: "approval" },
  { key: "data", label: "数据管理", icon: "analytics" },
  { key: "report", label: "报表中心", icon: "report" },
  { key: "permission", label: "用户与权限", icon: "customer" },
  { key: "setting", label: "基础配置", icon: "setting" },
];

export const glassMetrics: MetricItem[] = [
  {
    id: "sales",
    label: "总销售额",
    value: "¥ 632,316.00",
    delta: "12.45%",
    trend: [26, 31, 29, 36, 34, 45, 28, 35, 49, 41, 46, 48],
    tone: "blue",
    icon: "finance",
  },
  {
    id: "orders",
    label: "订单总数",
    value: "1,235",
    delta: "8.21%",
    trend: [18, 24, 22, 29, 21, 16, 25, 38, 44, 32, 34, 36],
    tone: "green",
    icon: "order",
  },
  {
    id: "customers",
    label: "新增客户",
    value: "263",
    delta: "15.32%",
    trend: [20, 26, 22, 30, 25, 18, 22, 31, 28, 35, 39, 41],
    tone: "purple",
    icon: "customer",
  },
  {
    id: "payment",
    label: "回款金额",
    value: "¥ 165,231.00",
    delta: "10.05%",
    trend: [19, 22, 24, 21, 27, 20, 31, 29, 42, 35, 39, 40],
    tone: "orange",
    icon: "finance",
  },
  {
    id: "todo",
    label: "待办事项",
    value: "28",
    delta: "6.67%",
    trend: [16, 18, 15, 17, 19, 14, 18, 29, 24, 31, 38, 42],
    tone: "blue",
    icon: "task",
    direction: "down",
  },
];

export const mintMetrics: MetricItem[] = [
  {
    id: "revenue",
    label: "营业收入",
    value: "¥ 8,856,200",
    delta: "12.6%",
    trend: [30, 34, 40, 36, 44, 42, 49, 46, 55, 52, 58, 69],
    tone: "mint",
    icon: "finance",
  },
  {
    id: "orderCount",
    label: "订单数",
    value: "12,568",
    delta: "8.3%",
    trend: [24, 28, 34, 31, 36, 35, 41, 38, 49, 45, 52, 48],
    tone: "green",
    icon: "order",
  },
  {
    id: "newCustomers",
    label: "新增客户数",
    value: "2,352",
    delta: "15.7%",
    trend: [18, 25, 23, 30, 39, 34, 43, 41, 49, 47, 55, 51],
    tone: "cyan",
    icon: "customer",
  },
  {
    id: "unitPrice",
    label: "客单价",
    value: "¥ 706.48",
    delta: "2.1%",
    trend: [50, 48, 39, 41, 34, 47, 32, 36, 49, 38, 36, 28],
    tone: "red",
    icon: "business",
    direction: "down",
  },
  {
    id: "repurchase",
    label: "复购率",
    value: "28.6%",
    delta: "4.8%",
    trend: [26, 28, 33, 30, 36, 34, 42, 39, 48, 45, 56, 66],
    tone: "mint",
    icon: "analytics",
  },
  {
    id: "refund",
    label: "退款率",
    value: "1.23%",
    delta: "0.3%",
    trend: [28, 22, 18, 26, 20, 30, 31, 43, 24, 22, 25, 20],
    tone: "red",
    icon: "finance",
    direction: "down",
  },
];

export const opsMetrics: MetricItem[] = [
  {
    id: "traffic",
    label: "平台总访问量",
    value: "32,568,129",
    delta: "12.6%",
    trend: [34, 38, 32, 40, 45, 38, 44, 39, 48, 51, 47, 55],
    tone: "blue",
    icon: "analytics",
  },
  {
    id: "activeUsers",
    label: "今日活跃用户",
    value: "128,932",
    delta: "8.4%",
    trend: [24, 29, 26, 37, 31, 43, 34, 46, 41, 52, 49, 54],
    tone: "purple",
    icon: "customer",
  },
  {
    id: "newUsers",
    label: "今日新增用户",
    value: "6,732",
    delta: "15.3%",
    trend: [18, 22, 30, 28, 35, 38, 34, 44, 40, 49, 52, 51],
    tone: "cyan",
    icon: "user",
  },
  {
    id: "tasks",
    label: "系统总任务数",
    value: "24,732",
    delta: "3.8%",
    trend: [28, 35, 29, 31, 44, 38, 42, 39, 48, 45, 51, 49],
    tone: "purple",
    icon: "task",
  },
];

export const quickActions: QuickAction[] = [
  { id: "customer", label: "新增客户", icon: "customer", tone: "blue" },
  { id: "order", label: "新增订单", icon: "cart", tone: "green" },
  { id: "contract", label: "合同管理", icon: "contract", tone: "orange" },
  { id: "approval", label: "发起审批", icon: "approval", tone: "blue" },
  { id: "report", label: "数据报表", icon: "report", tone: "purple" },
  { id: "product", label: "产品管理", icon: "product", tone: "red" },
  { id: "ticket", label: "工单管理", icon: "ticket", tone: "purple" },
  { id: "finance", label: "费用报销", icon: "finance", tone: "mint" },
  { id: "task", label: "任务管理", icon: "task", tone: "blue" },
  { id: "app", label: "更多应用", icon: "app", tone: "slate" },
];

export const rankingItems: RankingItem[] = [
  { id: "east", rank: 1, name: "华东区销售部", amount: "¥ 126,560" },
  { id: "south", rank: 2, name: "华南区销售部", amount: "¥ 98,312" },
  { id: "north", rank: 3, name: "华北区销售部", amount: "¥ 87,453" },
  { id: "west", rank: 4, name: "西南区销售部", amount: "¥ 65,231" },
  { id: "central", rank: 5, name: "华中区销售部", amount: "¥ 54,760" },
];

export const activities: ActivityItem[] = [
  { id: "a1", content: "系统管理员 创建了新用户：张三", time: "2分钟前", tone: "blue" },
  { id: "a2", content: "订单编号 SO-20260310001 已完成", time: "15分钟前", tone: "cyan" },
  { id: "a3", content: "客户 北京某某科技有限公司 已签约", time: "1小时前", tone: "green" },
  { id: "a4", content: "审批流程 合同审批 已通过", time: "2小时前", tone: "red" },
  { id: "a5", content: "财务到账 ¥25,000.00", time: "3小时前", tone: "orange" },
];

export const notices: NoticeItem[] = [
  {
    id: "n1",
    title: "系统升级通知",
    description: "系统将在 2026-03-12 02:00-04:00 进行升级",
    time: "10:30",
    tone: "mint",
  },
  {
    id: "n2",
    title: "数据报表更新",
    description: "《2026年Q1运营分析报表》已更新完成",
    time: "09:15",
    tone: "blue",
  },
  {
    id: "n3",
    title: "新功能上线",
    description: "智能客服助手 2.0 版本正式上线",
    time: "昨日 17:45",
    tone: "orange",
  },
  {
    id: "n4",
    title: "安全提醒",
    description: "检测到异常登录行为，请及时查看",
    time: "昨日 14:22",
    tone: "purple",
  },
];

export const todos: TodoItem[] = [
  { id: "t1", title: "审核供应商入驻申请", owner: "审核", due: "今天 12:00", tone: "blue" },
  { id: "t2", title: "处理客户投诉工单", owner: "客服", due: "今天 15:00", tone: "cyan" },
  { id: "t3", title: "确认订单异常处理方案", owner: "运营", due: "明天 10:00", tone: "mint" },
  { id: "t4", title: "制定下周运营计划", owner: "运营", due: "03-12 09:00", tone: "blue" },
  { id: "t5", title: "财务对账与结算", owner: "财务", due: "03-12 16:00", tone: "orange" },
];

export const taskProgressItems: TaskProgressItem[] = [
  { id: "p1", title: "数据同步任务", percent: 85, status: "进行中", tone: "blue" },
  { id: "p2", title: "用户行为分析", percent: 65, status: "进行中", tone: "purple" },
  { id: "p3", title: "内容审核任务", percent: 90, status: "进行中", tone: "blue" },
  { id: "p4", title: "报表生成任务", percent: 40, status: "等待中", tone: "purple" },
  { id: "p5", title: "系统备份任务", percent: 100, status: "已完成", tone: "mint" },
];

export const workOrders: WorkOrderRecord[] = [
  {
    key: "WO-20240524001",
    id: "WO-20240524001",
    title: "用户反馈：页面加载缓慢",
    status: "pending",
    priority: "medium",
    owner: "李明",
    avatar: "李",
    department: "运营部",
    createdAt: "2024-05-24 09:41",
    updatedAt: "2024-05-24 10:15",
    source: "用户反馈",
    contact: "138****5678",
    relatedSystem: "运营管理平台",
    description:
      "用户反馈在打开数据列表页面时，加载时间较长，影响使用体验，请排查页面并优化。",
    attachmentName: "错误截图.png",
    timeline: [
      { id: "tl1", title: "工单创建", operator: "系统", time: "2024-05-24 09:41:23" },
      { id: "tl2", title: "指派给 李明", operator: "张伟", time: "2024-05-24 09:42:10" },
      { id: "tl3", title: "状态变更为 待处理", operator: "系统", time: "2024-05-24 09:42:10" },
    ],
  },
  {
    key: "WO-20240523018",
    id: "WO-20240523018",
    title: "数据导出功能异常",
    status: "processing",
    priority: "high",
    owner: "王芳",
    avatar: "王",
    department: "技术部",
    createdAt: "2024-05-23 16:20",
    updatedAt: "2024-05-24 11:02",
    source: "系统告警",
    contact: "export@demo.local",
    relatedSystem: "报表中心",
    description: "导出大批量数据时偶发失败，需要补充重试和失败提示。",
    attachmentName: "export-log.txt",
    timeline: [
      { id: "tl1", title: "工单创建", operator: "系统", time: "2024-05-23 16:20:00" },
      { id: "tl2", title: "开始处理", operator: "王芳", time: "2024-05-24 09:20:00" },
    ],
  },
  {
    key: "WO-20240523017",
    id: "WO-20240523017",
    title: "权限申请：新增角色",
    status: "pending",
    priority: "medium",
    owner: "张伟",
    avatar: "张",
    department: "运营部",
    createdAt: "2024-05-23 15:10",
    updatedAt: "2024-05-24 09:50",
    source: "权限申请",
    contact: "zhangwei",
    relatedSystem: "权限中心",
    description: "新增区域运营角色，并绑定对应页面菜单与数据权限。",
    attachmentName: "role-scope.xlsx",
    timeline: [
      { id: "tl1", title: "工单创建", operator: "系统", time: "2024-05-23 15:10:00" },
    ],
  },
  {
    key: "WO-20240522012",
    id: "WO-20240522012",
    title: "系统报错：接口超时",
    status: "processing",
    priority: "high",
    owner: "陈强",
    avatar: "陈",
    department: "技术部",
    createdAt: "2024-05-22 11:32",
    updatedAt: "2024-05-24 08:45",
    source: "系统告警",
    contact: "ops-monitor",
    relatedSystem: "服务网关",
    description: "接口响应时间超过阈值，需定位慢请求来源。",
    attachmentName: "trace-id.txt",
    timeline: [
      { id: "tl1", title: "告警转工单", operator: "系统", time: "2024-05-22 11:32:00" },
      { id: "tl2", title: "排查链路追踪", operator: "陈强", time: "2024-05-23 09:00:00" },
    ],
  },
  {
    key: "WO-20240521009",
    id: "WO-20240521009",
    title: "数据修正：统计偏差",
    status: "done",
    priority: "medium",
    owner: "李明",
    avatar: "李",
    department: "运营部",
    createdAt: "2024-05-21 10:05",
    updatedAt: "2024-05-23 17:20",
    source: "数据巡检",
    contact: "data-team",
    relatedSystem: "经营看板",
    description: "修复日报统计口径中的重复计数问题。",
    attachmentName: "check-result.xlsx",
    timeline: [
      { id: "tl1", title: "工单创建", operator: "系统", time: "2024-05-21 10:05:00" },
      { id: "tl2", title: "完成处理", operator: "李明", time: "2024-05-23 17:20:00" },
    ],
  },
  {
    key: "WO-20240520007",
    id: "WO-20240520007",
    title: "功能建议：批量导入",
    status: "done",
    priority: "low",
    owner: "王芳",
    avatar: "王",
    department: "产品部",
    createdAt: "2024-05-20 14:22",
    updatedAt: "2024-05-22 16:18",
    source: "用户反馈",
    contact: "product-feedback",
    relatedSystem: "客户管理",
    description: "客户希望新增批量导入入口，降低重复录入成本。",
    attachmentName: "import-template.xlsx",
    timeline: [
      { id: "tl1", title: "工单创建", operator: "系统", time: "2024-05-20 14:22:00" },
      { id: "tl2", title: "需求进入排期", operator: "王芳", time: "2024-05-22 16:18:00" },
    ],
  },
  {
    key: "WO-20240519003",
    id: "WO-20240519003",
    title: "账号无法登录",
    status: "cancelled",
    priority: "low",
    owner: "张伟",
    avatar: "张",
    department: "运营部",
    createdAt: "2024-05-19 09:18",
    updatedAt: "2024-05-20 10:11",
    source: "用户反馈",
    contact: "user-login",
    relatedSystem: "登录中心",
    description: "重复提交工单，已合并到主工单处理。",
    attachmentName: "login.png",
    timeline: [
      { id: "tl1", title: "工单创建", operator: "系统", time: "2024-05-19 09:18:00" },
      { id: "tl2", title: "取消并合并", operator: "张伟", time: "2024-05-20 10:11:00" },
    ],
  },
];
