import { createFormSchema } from "@/shared/form-schema";

export default createFormSchema({
  formMeta: {
    formUuid: "",
    appType: process.env.OPENXIANGDA_APP_TYPE || "APP_XXXX",
    title: "服务工单",
  },
  fields: [
    {
      fieldId: "title",
      componentName: "TextField",
      label: "标题",
      required: true,
      placeholder: "请输入工单标题",
    },
    {
      fieldId: "status",
      componentName: "SelectField",
      label: "状态",
      required: true,
      placeholder: "请选择工单状态",
      defaultValue: { label: "新建", value: "new" },
      options: [
        { label: "新建", value: "new" },
        { label: "已受理", value: "accepted" },
        { label: "处理中", value: "processing" },
        { label: "挂起", value: "paused" },
        { label: "已解决", value: "resolved" },
        { label: "已关闭", value: "closed" },
        { label: "已取消", value: "cancelled" },
      ],
    },
    {
      fieldId: "priority",
      componentName: "SelectField",
      label: "优先级",
      placeholder: "请选择优先级",
      defaultValue: { label: "普通", value: "normal" },
      options: [
        { label: "紧急", value: "urgent" },
        { label: "高", value: "high" },
        { label: "普通", value: "normal" },
        { label: "低", value: "low" },
      ],
    },
    {
      fieldId: "currentOwner",
      componentName: "UserSelectField",
      label: "当前处理人",
      placeholder: "请选择当前处理人",
    },
    {
      fieldId: "college",
      componentName: "SelectField",
      label: "所属学院",
      placeholder: "请选择所属学院",
      showSearch: true,
      allowClear: true,
      options: [],
      valueSync: [{ targetFieldId: "collegeScopeKey", valuePath: "value" }],
      optionSource: {
        type: "linkedForm",
        linkedForm: {
          formUuid: "FORM_COLLEGE_PROFILE",
          fieldId: "collegeName",
          labelFieldId: "collegeName",
          valueFieldId: "collegeCode",
          searchFieldId: "collegeName",
          sortField: "collegeName",
          pageSize: 20,
          remoteSearch: true,
          deduplicate: true,
        },
      },
    },
    {
      fieldId: "classGroup",
      componentName: "SelectField",
      label: "所属班级",
      placeholder: "请选择所属班级",
      showSearch: true,
      allowClear: true,
      options: [],
      valueSync: [{ targetFieldId: "classScopeKey", valuePath: "value" }],
      optionSource: {
        type: "linkedForm",
        linkedForm: {
          formUuid: "FORM_CLASS_PROFILE",
          fieldId: "className",
          labelFieldId: "className",
          valueFieldId: "classCode",
          searchFieldId: "className",
          sortField: "className",
          pageSize: 20,
          remoteSearch: true,
          deduplicate: true,
        },
      },
    },
    {
      fieldId: "ownerUserScopeKey",
      componentName: "TextField",
      label: "负责人权限键",
      behavior: "HIDDEN",
    },
    {
      fieldId: "ownerDeptScopeKey",
      componentName: "TextField",
      label: "负责部门权限键",
      behavior: "HIDDEN",
    },
    {
      fieldId: "collegeScopeKey",
      componentName: "TextField",
      label: "学院权限键",
      behavior: "HIDDEN",
    },
    {
      fieldId: "classScopeKey",
      componentName: "TextField",
      label: "班级权限键",
      behavior: "HIDDEN",
    },
    {
      fieldId: "requester",
      componentName: "UserSelectField",
      label: "提交人",
      required: true,
      placeholder: "请选择提交人",
    },
    {
      fieldId: "description",
      componentName: "TextAreaField",
      label: "问题描述",
      required: true,
      placeholder: "请描述问题现象、影响范围和期望处理结果",
    },
    {
      fieldId: "lastActionAt",
      componentName: "DateField",
      label: "最近操作时间",
      behavior: "HIDDEN",
    },
    {
      fieldId: "attachments",
      componentName: "AttachmentField",
      label: "附件",
      placeholder: "请上传问题相关附件",
      maxCount: 8,
    },
  ],
});
